apache/doris-flink-connector

.gitignore
flink-doris-connector/pom.xml

Try to solve the error when executing "mvn release:prepare"

[chore] add maven-release-plugin plugin

---

flink-doris-connector/pom.xml

[chore] change the repo name

---

flink-doris-connector/pom.xml

[chore] add maven-gpg-plugin

---

.github/workflows/build-extension.yml
README.md
flink-doris-connector/build.sh

[chore] modify build.sh and github action for 1.14

---

flink-doris-connector/src/main/java/org/apache/doris/flink/rest/RestService.java

目前，使用 flink-doris-connector 写入 Doris ，当配置了多个 Doris FE 节点的前提下， 内部通过 FE 节点请求到 BE 时会随机选择其中一个 FE 提交 http 请求 BE 节点地址；在生产环境中，由于机器原因或者是版本升级需要滚动重启 FE 服务时，由于某个 FE 服务暂时不可用，可能会引起 flink 作业异常退出；
为了降低集群变更或偶发异常影响实时流稳定，考虑通过对所有配置的  Doris FE 节点发送 http 请求查询 Doris BE。
Currently, when Flink-doris-Connetor writes Doris, it will queries Doris FE node through one of the Doris BE nodes randomly. It may causing job failures when one of Doris BE node in cluster is out of service. For example, sometime  machine has problem and need to restart or admin need to Actively restart service In the process of upgrading the version
5. Are there …

[feature]Supports traversal of Doris FE nodes when searching for Doris BE on branch flink-before-1.13

---

.asf.yaml
flink-doris-connector/build.sh
flink-doris-connector/pom.xml

1. modify GAV to "flink-doris-connector-{flink.minor.version}_${scala_version}"

[chore] change the GAV

---

flink-doris-connector/pom.xml

[chore] Change project name

---

flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/GenericDorisSinkFunction.java
flink-doris-connector/src/main/java/org/apache/doris/flink/datastream/DorisSourceFunction.java
flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicOutputFormat.java
flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisStreamLoad.java
flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisTableInputSplit.java

[Bug] Inconsistent id when deserializing 

---

flink-doris-connector/src/main/java/org/apache/doris/flink/serialization/RowBatch.java
flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSource.java
flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisRowDataInputFormat.java
flink-doris-connector/src/test/java/org/apache/doris/flink/serialization/TestRowBatch.java

Issue Number: close #25 
Add deserialize in DorisRowDataInputFormat.nextRecord
This is a small bug.

[Bug] Fix row type decimal convert bug

---

flink-doris-connector/src/main/java/org/apache/doris/flink/serialization/RowBatch.java
flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSource.java
flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisRowDataInputFormat.java
flink-doris-connector/src/test/java/org/apache/doris/flink/serialization/TestRowBatch.java

Issue Number: close #25 
Add deserialize in DorisRowDataInputFormat.nextRecord
This is a small bug.

[Bug-1.13] Fix row type decimal convert bug

---

flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisReadOptions.java
flink-doris-connector/src/main/java/org/apache/doris/flink/deserialization/converter/DorisRowConverter.java
flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSource.java

Issue Number: close #28 
fix flink schema and doris schema column not mapping

[Bug] fix flink schema and doris schema column not mapping

---

.gitignore
README.md
flink-doris-connector/src/test/java/org/apache/doris/flink/deserialization/RowDataDeserializationSchemaTest.java
flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/TestDorisWriter.java
flink-doris-connector/src/test/java/org/apache/doris/flink/source/DorisSourceExampleTest.java
flink-doris-connector/src/test/java/org/apache/doris/flink/table/DorisDynamicTableSourceTest.java

- Update documentation link
- Fix some UTs that cannot run locally

Fix broke URL and UT

---

README.md

[Doc] Remove incubating

---

CONTRIBUTING.md
CONTRIBUTING_CN.md
DISCLAIMER
NOTICE.txt
README.md

[doc]link fix

---

CONTRIBUTING.md
CONTRIBUTING_CN.md
DISCLAIMER
NOTICE.txt
README.md
flink-doris-connector/pom.xml

Log4j upgrade

---

flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisExecutionOptions.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisStreamLoad.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisWriter.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/LabelGenerator.java
flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableFactory.java
flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/TestDorisStreamLoad.java
flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/TestDorisWriter.java

add 2pc config

---

.asf.yaml

[TLP] remove incubator

---

.gitignore

Issue Number: #57
.gitignore added *.DS_Store

feat(.gitignore): added *.DS_Store

---

flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/DorisCatalog.java
flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/DorisCatalogFactory.java
flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/DorisCatalogOptions.java
flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/DorisTypeMapper.java
flink-doris-connector/src/main/java/org/apache/doris/flink/source/reader/DorisSourceSplitReader.java
flink-doris-connector/src/main/java/org/apache/doris/flink/source/reader/DorisValueReader.java
flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisConfigOptions.java
flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableFactory.java
flink-doris-connector/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
flink-doris-connector/src/test/java/org/apache/doris/flink/catalog/CatalogTest.java
flink-doris-connector/src/test/java/org/apache/doris/flink/source/reader/DorisSourceReaderTest.java

**1.support doris catalog**
In flink1.15 the following operations can be performed
```sql
Flink SQL> CREATE CATALOG doris_catalog WITH(
>     'type' = 'doris',
>     'default-database' = 'test',
>     'username' = 'root',
>     'password' = '',
>     'jdbc-url' = 'jdbc:mysql://127.0.0.1:9030',
>     'sink.label-prefix' = 'label'
> );
[INFO] Execute statement succeed.
Flink SQL> CREATE CATALOG my_catalog WITH(
>     'type' = 'jdbc',
>     'default-database' = 'test',
>     'username' = 'root',
>     'password' = '',
>     'base-url' = 'jdbc:mysql://127.0.0.1:3306'
> );
[INFO] Execute statement succeed.
Flink SQL> use catalog doris_catalog;
[INFO] Execute statement succeed.
Flink SQL> show tables;
+---------------------------+
|                table name | …
```

[Feature] support doris catalog

---

flink-doris-connector/src/main/java/org/apache/doris/flink/rest/RestService.java
flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSink.java

[improvement] fix uniq delete operation

---

flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/GenericDorisSinkFunction.java
flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSink.java

#4 
This pr seems to be lost when it is merged
https://github.com/apache/doris-flink-connector/pull/4/files

[Fix] add miss pr4

---

.gitignore
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/RowSerializer.java
flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/TestRowSerializer.java

Issue Number: #70 
ADD RowSerializer AND ut
2. Has unit tests been added: (Yes)
3. Has document been added or modified: (No,but will)

[Enhancement] ADD RowSerializer for doris flink connector

---

flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableFactory.java

[Bug] fix flinksql sink parallelism

---

flink-doris-connector/pom.xml
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/HttpGetWithEntity.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/HttpPutBuilder.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/committer/DorisCommitter.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisStreamLoad.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisWriter.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/JsonDebeziumSchemaSerializer.java
flink-doris-connector/src/main/resources/log4j.properties
flink-doris-connector/src/test/java/org/apache/doris/flink/CDCSchemaChangeExample.java
flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/TestJsonDebeziumSchemaSerializer.java
flink-doris-connector/src/test/java/org/apache/doris/flink/utils/DateToStringConverter.java

[Feature] support 1.15 schema change

---

flink-doris-connector/src/main/java/org/apache/doris/flink/sink/LoadStatus.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisStreamLoad.java
flink-doris-connector/src/test/java/org/apache/doris/flink/sink/HttpTestUtil.java
flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/TestDorisStreamLoad.java

[fix] Add log in abort phase

---

flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/DorisTypeMapper.java
flink-doris-connector/src/main/java/org/apache/doris/flink/serialization/RowBatch.java
flink-doris-connector/src/main/thrift/doris/Types.thrift

[Feature](Type)add new type of doris-flink-connector

---

flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisStreamLoad.java

[Fix](flink-connector)fix stream load exit unnormally as concurrency issue

---

flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/DorisTypeMapper.java
flink-doris-connector/src/main/java/org/apache/doris/flink/serialization/RowBatch.java

[Feature](Type)add new type jsonb of doris-flink-connector

---

.github/workflows/build-extension.yml

fix thrift compiler

---

flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/JsonDebeziumSchemaSerializer.java

fix decimal(65,18) loss of precision

---

flink-doris-connector/src/main/java/org/apache/doris/flink/rest/RestService.java
flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSink.java

Issue Number: close #111 
1. set timeout for rest service http request
2. optimize code logic to avoid non-necessary http request
3. Has unit tests been added: (No)
4. Has document been added or modified: (No Need)
5. Does it need to update dependencies: (No)
6. Are there any changes that cannot be rolled back: (No)

add time for rest service request and some minor improvement

---

flink-doris-connector/src/main/java/org/apache/doris/flink/sink/committer/DorisCommitter.java

commitTransaction method improvement

commitTransaction method improvement

---

flink-doris-connector/pom.xml

[fix](pom)update pom version

---

flink-doris-connector/src/main/java/org/apache/doris/flink/backend/BackendClient.java

minor optimize

---

flink-doris-connector/src/main/java/org/apache/doris/flink/deserialization/converter/DorisRowConverter.java
flink-doris-connector/src/main/java/org/apache/doris/flink/serialization/RowBatch.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/RowDataSerializer.java
flink-doris-connector/src/test/java/org/apache/doris/flink/DorisSinkArraySQLExample.java
flink-doris-connector/src/test/java/org/apache/doris/flink/DorisSourceSinkExample.java
flink-doris-connector/src/test/java/org/apache/doris/flink/lookup/LookupJoinCdcExample.java

Support doris array type and  FlinkSQLarray,map,row type
fix datetimev2 bug,when datetimev2 milliseconds less than 6 digits

[Feature](type) Support doris array type and  FlinkSQLarray,map,row type

---

flink-doris-connector/src/main/java/org/apache/doris/flink/rest/RestService.java

get connection response improvement

get connection response improvement

---

flink-doris-connector/src/main/java/org/apache/doris/flink/source/split/DorisSourceSplitSerializer.java

When there are too many tablets, in the case of full table scan, the query_plan will be too long, and the error may be reported as follows
This pr is to replace writeUTF with writeInt and write

[improve]fix source when query plan is too long

---

flink-doris-connector/src/main/java/org/apache/doris/flink/sink/committer/DorisCommitter.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisStreamLoad.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisWriter.java
flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/TestDorisStreamLoad.java

[improve] improve log print

---

README.md
flink-doris-connector/build.sh
flink-doris-connector/pom.xml

update build.sh for upgrade to 1.17

[improvement] update build.sh and pom for support 1.15-1.17

---

flink-doris-connector/src/main/java/org/apache/doris/flink/deserialization/converter/DorisRowConverter.java
flink-doris-connector/src/test/java/org/apache/doris/flink/lookup/LookupJoinCdcExample.java

fix doris lookup join in date type

[Fix] fix doris lookup join date type

---

flink-doris-connector/src/main/java/org/apache/doris/flink/rest/RestService.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/JsonDebeziumSchemaSerializer.java

[fix] Fix the exception when formatting url

---

flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/JsonDebeziumSchemaSerializer.java

fix query schema change

---

flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisWriter.java

[BugFix](checkDone) fix interrupt issue

---

NOTICE.txt

Update year NOTICE.txt

---

flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mysql/MysqlDatabaseSync.java

add jdbcProperties options

---

flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java

Issue Number: close #149 
Fix issue 149 by appointing a unique uid to each sink operator.
2. Has unit tests been added: No
3. Has document been added or modified: No

Fix issue 149 by appointing a unique uid to each sink operator.

---

README.md

[typo](docs) modify the invalid uri in README.md

---

flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/doris/DorisSystem.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/SourceSchema.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/oracle/OracleDatabaseSync.java

Oracle no primary key table synchronization

[improvement] Oracle no primary key table synchronization

---

flink-doris-connector/src/main/java/org/apache/doris/flink/serialization/RowBatch.java
flink-doris-connector/src/test/java/org/apache/doris/flink/DorisSourceExample.java

this fix by https://github.com/apache/doris/pull/19091

[fix] fixed largeint type reads to adapt to Doris 2.0

---

flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DateToStringConverter.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/sqlserver/SqlServerType.java

fix mysql timezone and add sqlserver type

[Fix] fix mysql timezone and add sqlserver type

---

flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicOutputFormat.java

DorisExecutionOptions setEnableDelete() does not take effect in this verion.
2. Has unit tests been added: No
3. Has document been added or modified: No Need

[Fix] fix setting error

---

flink-doris-connector/pom.xml

[improve] update flink cdc pom.xml 

---

flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/JsonDebeziumSchemaSerializer.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/SchemaChangeHelper.java
flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/SchemaChangeHelperTest.java
flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/TestJsonDebeziumSchemaSerializer.java

schema change support rename column.

[Improve](schemaChange)schema change support rename column

---

flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mysql/MysqlDatabaseSync.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/oracle/OracleDatabaseSync.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/postgres/PostgresDatabaseSync.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/sqlserver/SqlServerDatabaseSync.java

[Improve] registerDriver improvement
Before get jdbc connection, we need ensure that the driver has been registered, otherwise unexpected bugs may occur. 🐛

[Improve] registerDriver improvement

---

flink-doris-connector/pom.xml

update branch-for-flink-before-1.13 pom version to 1.0.4

update version in pom.xml

---

flink-doris-connector/src/main/java/org/apache/doris/flink/sink/ResponseUtil.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisWriter.java
flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableFactory.java

[improve] commit message compatible

---

flink-doris-connector/src/main/java/org/apache/doris/flink/rest/RestService.java

skip table model check in multi table

[Bug] skip table model check in multi table

---

flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/postgres/PostgresType.java

Issue Number: #227 
use varchar type mapping logic for postgres character type

[Fix-227] fix character type mapping for postgres

---

flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisWriter.java

If you restore from checkpoint, the checkpoint table is tb1, but the newly imported table does not have tb1. You can abort normally, but an error will be reported during stopload.

[Bug] fix stopload bug when restore from checkpoint

---

flink-doris-connector/src/main/java/org/apache/doris/flink/sink/schema/SchemaChangeManager.java

[fix]fix SchemaChangeManager cannot serializable

---

flink-doris-connector/src/main/java/org/apache/doris/flink/sink/schema/SchemaChangeManager.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/JsonDebeziumSchemaSerializer.java

[fix]fix SchemaChangeManager cannot do schema change

---

flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/DorisTypeMapper.java
flink-doris-connector/src/main/java/org/apache/doris/flink/deserialization/converter/DorisRowConverter.java

1. Modify the serialization method to be static to facilitate external use.
2. Modify the catalog’s type mapping to synchronize and unify it with the entire library.

[improve] some improve for package

---

flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/TestJsonDebeziumSchemaSerializer.java

[fix]Fix testExtractDDLListMultipleColumns unit test

---

flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/JsonDebeziumSchemaSerializer.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mysql/MysqlDatabaseSync.java

fix can not create table problem

[Bug] fix can not create table problem

---

.github/workflows/checkstyle.yaml
README.md

Add document for code style.
Related PR: https://github.com/apache/doris-flink-connector/pull/269 https://github.com/apache/doris-flink-connector/pull/272

[step3][doc]add document for code style

---

flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mysql/MysqlType.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/oracle/OracleType.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/postgres/PostgresType.java

[buf](fix) fix inaccurate mapping of RDMS datetime/timestamp to Doris

---

flink-doris-connector/pom.xml

[Chore] update connector version to 1.6.0

---

flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/doris/DorisSystem.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/schema/SchemaChangeHelper.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/schema/SchemaChangeManager.java
flink-doris-connector/src/test/java/org/apache/doris/flink/sink/schema/SchemaChangeHelperTest.java
flink-doris-connector/src/test/java/org/apache/doris/flink/sink/schema/SchemaManagerTest.java
flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/TestJsonDebeziumSchemaChangeImplV2.java

cdc adds references when schema changes to prevent errors when keywords are added.

[Improve](cdc) Column add quote in schema change

---

flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mysql/MysqlType.java

add mysql set type for type mapping

[improve](cdc) add mysql set type for type mapping

---

flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/oracle/OracleDatabaseSync.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/sqlserver/SqlServerDatabaseSync.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/sqlserver/SqlServerType.java

[fix](cdc)resolve the issue of automatic table creation failure in SQL Server due to the presence of the `systranschemas` 

---

flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisStreamLoad.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisWriter.java
flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/TestDorisStreamLoad.java

[Bug] Fix log printing error

---

flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/CdcDataChange.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/CdcSchemaChange.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/JsonDebeziumDataChange.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/JsonDebeziumSchemaChange.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/JdbcSourceSchema.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/ParsingProcessFunction.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/SourceSchema.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mysql/MysqlSchema.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/oracle/OracleSchema.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/sqlserver/SqlServerSchema.java

Adjust the code framework related to CDC.

[improve] adjust the code framework related to CDC.

---

flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java

Issue Number:  #331 
There are some minor changes in class DatabaseSync. Modify the function buildSchemaSerializer of DatabaseSync.
1. Does it affect the original behavior: (Yes/No/I Don't know) No
2. Has unit tests been added: (Yes/No/No Need) No
3. Has document been added or modified: (Yes/No/No Need) No
4. Does it need to update dependencies: (Yes/No) No
5. Are there any changes that cannot be rolled back: (Yes/No) No

[Bug] Fix the invalid options --table-prefix and --table-suffix (#331)

---

flink-doris-connector/src/main/java/org/apache/doris/flink/sink/HttpUtil.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/batch/DorisBatchStreamLoad.java

add http timeout for batch write

[improvement] add http timeout for batch write

---

.github/workflows/build-connector.yml
README.md
flink-doris-connector/build.sh

[Improve] Support flink1.19

---

flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/JsonDebeziumSchemaSerializer.java

[fix]Fix BigDecimal precision missing

---

flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSource.java

[Chore] remove unuse comment

---

flink-doris-connector/src/main/java/org/apache/doris/flink/rest/RestService.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/schema/SchemaChangeManager.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/JsonDebeziumSchemaChangeImplV2.java
flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/TestJsonDebeziumSchemaChangeImplV2.java

[fix]Fix the first schema change does not take effect when the source  table has no data

---

flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/JdbcSourceSchema.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/SourceSchema.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/oracle/OracleDatabaseSync.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/oracle/OracleSchema.java

If the Oracle table we synchronize contains "/", it will cause ORA-01424 when retrieving column information through JDBC. This can be resolved by replacing "/" with "_".
The error as following:
```
Exception in thread "main" java.sql.SQLDataException: ORA-01424: 转义符之后字符缺失或非法
at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461)
at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104)
at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:550)
at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268)
at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:229)
at oracle.jdbc.driver.T4CStatement.fetch(T4CStatement.java:1037)
at …
```

[fix](cdc)fix the issue caused by Oracle table names containing slash

---

flink-doris-connector/pom.xml
flink-doris-connector/src/main/java/org/apache/doris/flink/serialization/RowBatch.java
flink-doris-connector/src/test/java/org/apache/doris/flink/serialization/TestRowBatch.java

[improve] support read variant type

---

flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisExecutionOptions.java
flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisStreamOptions.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/DorisSink.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/copy/DorisCopyWriter.java
flink-doris-connector/src/test/java/org/apache/doris/flink/DorisSinkBatchExample.java

[fix] fix the enable.batch-mode option not working

---

flink-doris-connector/src/main/java/org/apache/doris/flink/lookup/LookupMetrics.java
flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisRowDataAsyncLookupFunction.java
flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisRowDataJdbcLookupFunction.java
flink-doris-connector/src/main/java/org/apache/doris/flink/table/LookupMetrics.java

Add lookup mertic
hitCount: the number of cache hits
missCount: the number of cache misses
loadCount: the number of times put into cache

[improve] add lookup mertics

---

flink-doris-connector/pom.xml
flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/doris/DorisSystem.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/MongoDBJsonDebeziumSchemaSerializer.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/CdcDataChange.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/MongoJsonDebeziumDataChange.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/MongoJsonDebeziumSchemaChange.java
flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisConfigOptions.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/CdcTools.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mongodb/ChangeStreamConstant.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mongodb/MongoDBDatabaseSync.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mongodb/MongoDBSchema.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mongodb/MongoDBType.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mongodb/MongoDateConverter.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mongodb/MongoParsingProcessFunction.java
flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcMongoSyncDatabaseCase.java

Add the function of synchronizing data to Doris through mongodb cdc
The example is as follows:
-Dexecution.checkpointing.interval=10s\
-Dparallelism.default=1\
-c org.apache.doris.flink.tools.cdc.CdcTools\
./lib/flink-doris-connector-1.18-1.6.0-SNAPSHOT.jar \
mongodb-sync-database \
--database cdc_test\
--mongodb-conf hosts=127.0.0.1:27017 \
--mongodb-conf username=flinkuser \
--mongodb-conf password=flinkpwd \
--mongodb-conf database=test \
--mongodb-conf scan.startup.mode=initial \
--mongodb-conf schema.sample-percent=1 \
--including-tables cdc_test \
--sink-conf fenodes=127.0.0.1:8030 \
--sink-conf username=root \
--sink-conf password=\
--sink-conf jdbc-url=jdbc:mysql://127.0.0.1:9030 \
--sink-conf sink.label-prefix=label \
--sink-conf sink.enable-2pc=false \ …

[WIP](cdc) add MongoDB cdc

---

flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/postgres/PostgresDatabaseSync.java

[improve](cdc) support synchronization of PostgreSQL partitioned tables 

---

flink-doris-connector/pom.xml
flink-doris-connector/src/test/java/org/apache/doris/flink/DorisTestBase.java
flink-doris-connector/src/test/java/org/apache/doris/flink/sink/DorisSinkITCase.java
flink-doris-connector/src/test/java/org/apache/doris/flink/source/DorisSourceITCase.java
flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/DorisDorisE2ECase.java
flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/MySQLDorisE2ECase.java

[Improve] improve test Case

---

flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mongodb/MongoDBSchema.java
flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/mongodb/MongoDBSchemaTest.java
flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/mongodb/MongoDBTypeTest.java
flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/mongodb/MongoDateConverterTest.java
flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/mongodb/MongoParsingProcessFunctionTest.java

[improve](testcase) increase mongo cdc UT

---

flink-doris-connector/src/test/java/org/apache/doris/flink/sink/batch/TestDorisBatchStreamLoad.java

[improve](test-case) modify ut for batch streamload 

---

flink-doris-connector/src/main/java/org/apache/doris/flink/sink/HttpUtil.java

In the previous PR #344, the link is not reused in batch mode, and there may be potential problems in stream mode.

[Improve] Fix Httpclient connection in Stream Writer

---

flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/DorisTypeMapper.java
flink-doris-connector/src/test/java/org/apache/doris/flink/catalog/DorisTypeMapperTest.java

[improve](testcase) Increase case coverage

---

flink-doris-connector/src/main/java/org/apache/doris/flink/sink/HttpPutBuilder.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/batch/DorisBatchStreamLoad.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisStreamLoad.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/LoadConstants.java
flink-doris-connector/src/test/java/org/apache/doris/flink/sink/copy/TestDorisCopyWriter.java

support streamload group commit

[improve] support group commit

---

flink-doris-connector/src/main/java/org/apache/doris/flink/rest/RestService.java

Fix the problem of multiple fenodes when flink reads Doris

(Fix)[source] Fix the problem of multiple fenodes when flink reads Doris

---

flink-doris-connector/pom.xml

[Chore] Change Version to 1.6.2

---

flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java

This is a hot fix  for pr https://github.com/apache/doris-flink-connector/pull/371.

[hotfix] Fix the problem that the existing tables in Doris cannot be synchronized.

---

flink-doris-connector/src/main/java/org/apache/doris/flink/sink/schema/SchemaChangeManager.java

[fix]Fix the error of missing content returned by schema change response

---

flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/doris/FieldSchema.java
flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/doris/TableSchema.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/schema/SQLParserSchemaManager.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/JsonDebeziumChangeUtils.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/JsonDebeziumSchemaChange.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/JsonDebeziumSchemaChangeImplV2.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/SQLParserSchemaChange.java
flink-doris-connector/src/test/java/org/apache/doris/flink/sink/schema/SQLParserSchemaManagerTest.java
flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/TestJsonDebeziumChangeUtils.java
flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/TestJsonDebeziumSchemaChangeImplV2.java
flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/TestSQLParserSchemaChange.java
flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/MySQLDorisE2ECase.java

[improve]The sql_parser model of schema change support automatic table creation

---

flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableFactory.java

A simple comment typo
3. Has document been added or modified: No Need)

[typo] A simple comment typo

---

flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/MySQLDorisE2ECase.java

In the 1.6.2, if Doris had the same table as MySQL, data from MySQL would not be synchronized to Doris by Flink CDC, and flink-connector-doris-1.6.2.1 fixed it. Thus, the e2e case aims to prevent this problem.  

[test](cdc) add e2e test for MySql to Doris

---

flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/CdcTools.java
flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcToolsTest.java

[improve]cdc tools parameter removes leading and trailing spaces

---

flink-doris-connector/src/main/java/org/apache/doris/flink/source/DorisSource.java
flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSource.java
flink-doris-connector/src/test/java/org/apache/doris/flink/source/DorisSourceITCase.java

[Fix] SupportsFilterPushDown bug

---

flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/doris/DorisSystem.java
flink-doris-connector/src/main/java/org/apache/doris/flink/connection/SimpleJdbcConnectionProvider.java

[Improve]Release JDBC connection resources

---

flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/ConfigurationOptions.java
flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisReadOptions.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/JsonDebeziumSchemaChangeImplV2.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/SQLParserSchemaChange.java
flink-doris-connector/src/main/java/org/apache/doris/flink/source/reader/DorisValueReader.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
flink-doris-connector/src/test/java/org/apache/doris/flink/table/DorisDynamicTableFactoryTest.java

Increase the limit of doris.batch.size and change the default value, reference https://github.com/apache/doris/pull/35941/files

[Improve] add check for doris.batch.size

---

flink-doris-connector/pom.xml

This PR #465 commented out the arrow shade, which may cause conflicts with the client's own arrow dep, so it was added back.

[Chore] add arrow shade 

---

flink-doris-connector/src/main/java/org/apache/doris/flink/source/DorisSource.java
flink-doris-connector/src/main/java/org/apache/doris/flink/source/assigners/SimpleSplitAssigner.java
flink-doris-connector/src/main/java/org/apache/doris/flink/source/enumerator/DorisSourceEnumerator.java
flink-doris-connector/src/main/java/org/apache/doris/flink/source/reader/DorisSourceReader.java
flink-doris-connector/src/main/java/org/apache/doris/flink/source/reader/DorisSourceSplitReader.java

[Fix](source) fix source reader split cause npe

---

flink-doris-connector/src/test/java/org/apache/doris/flink/catalog/DorisCatalogFactoryTest.java
flink-doris-connector/src/test/java/org/apache/doris/flink/catalog/DorisCatalogITCase.java
flink-doris-connector/src/test/java/org/apache/doris/flink/container/e2e/Doris2DorisE2ECase.java
flink-doris-connector/src/test/java/org/apache/doris/flink/container/e2e/Mysql2DorisE2ECase.java
flink-doris-connector/src/test/java/org/apache/doris/flink/example/CDCSchemaChangeExample.java
flink-doris-connector/src/test/java/org/apache/doris/flink/example/CatalogExample.java
flink-doris-connector/src/test/java/org/apache/doris/flink/example/DorisDateAndTimestampSqlTest.java
flink-doris-connector/src/test/java/org/apache/doris/flink/example/DorisIntranetAccessSinkExample.java
flink-doris-connector/src/test/java/org/apache/doris/flink/example/DorisSinkArraySQLExample.java
flink-doris-connector/src/test/java/org/apache/doris/flink/example/DorisSinkBatchExample.java
flink-doris-connector/src/test/java/org/apache/doris/flink/example/DorisSinkExample.java
flink-doris-connector/src/test/java/org/apache/doris/flink/example/DorisSinkExampleRowData.java
flink-doris-connector/src/test/java/org/apache/doris/flink/example/DorisSinkMultiTableExample.java
flink-doris-connector/src/test/java/org/apache/doris/flink/example/DorisSinkSQLExample.java
flink-doris-connector/src/test/java/org/apache/doris/flink/example/DorisSinkStreamMultiTableExample.java
flink-doris-connector/src/test/java/org/apache/doris/flink/example/DorisSourceDataStream.java
flink-doris-connector/src/test/java/org/apache/doris/flink/example/DorisSourceExample.java
flink-doris-connector/src/test/java/org/apache/doris/flink/example/DorisSourceSinkExample.java
flink-doris-connector/src/test/java/org/apache/doris/flink/example/LookupJoinCdcExample.java
flink-doris-connector/src/test/java/org/apache/doris/flink/example/LookupJoinExample.java
flink-doris-connector/src/test/java/org/apache/doris/flink/sink/DorisSinkITCase.java
flink-doris-connector/src/test/java/org/apache/doris/flink/source/DorisSourceITCase.java
flink-doris-connector/src/test/java/org/apache/doris/flink/table/DorisDynamicTableFactoryTest.java

[Improve] improve case and extraction identifier config

---

flink-doris-connector/src/main/java/org/apache/doris/flink/sink/BackendUtil.java

In some cases, the httpcode will not return 200, but the service is still available.

[Fix] update response code for try connection

---

flink-doris-connector/src/test/java/org/apache/doris/flink/container/AbstractContainerTestBase.java
flink-doris-connector/src/test/java/org/apache/doris/flink/container/instance/ContainerService.java
flink-doris-connector/src/test/java/org/apache/doris/flink/container/instance/DorisContainer.java
flink-doris-connector/src/test/java/org/apache/doris/flink/container/instance/DorisCustomerContainer.java
flink-doris-connector/src/test/java/org/apache/doris/flink/container/instance/MySQLContainer.java
flink-doris-connector/src/test/java/org/apache/doris/flink/sink/DorisSinkITCase.java

In some scenarios, using a custom doris env will be more convenient for testing

[Improve](case) add customer doris container cluster

---

flink-doris-connector/pom.xml
flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisExecutionOptions.java
flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisOptions.java
flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisReadOptions.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/DorisSink.java
flink-doris-connector/src/main/java/org/apache/doris/flink/source/DorisSource.java

1. remove some dep
2. add DorisSource DorisSink and options builder comment

[Chore] improve dep and add builder comment

---

flink-doris-connector/src/test/java/org/apache/doris/flink/example/DorisSinkExample.java
flink-doris-connector/src/test/java/org/apache/doris/flink/example/DorisSinkExampleRowData.java
flink-doris-connector/src/test/java/org/apache/doris/flink/example/DorisSinkMultiTableExample.java
flink-doris-connector/src/test/java/org/apache/doris/flink/example/DorisSourceDataStream.java

[Chore](test) improve test example for doc

---

flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/JdbcSourceSchema.java

In some cases, when the primary key is empty, a detail table will be created by default. However, if there is a unique index, you can use the unique index as the primary key.

[Improvment](cdc) Use uniq index as primary key

---

flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mongodb/MongoDBDatabaseSync.java

[improvement][mongodb cdc]optimize startup performance

---

flink-doris-connector/pom.xml
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/postgres/PostgresDatabaseSync.java

[Improve](cdc) update cdc version to 3.2.1

---

flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DorisTableConfig.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/JdbcSourceSchema.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/SourceSchema.java
flink-doris-connector/src/test/resources/container/e2e/mysql2doris/testMySQL2DorisCreateTable.txt

In cdc create table, add --table-conf convert-uniq-to-pk=true

[improve](cdc) add config for uniq index to primary key with create table

---

flink-doris-connector/pom.xml
flink-doris-connector/src/main/java/org/apache/doris/flink/lookup/Worker.java
flink-doris-connector/src/main/java/org/apache/doris/flink/rest/RestService.java

fix connect timeout config and add prefix for lookup query

[Chore] Fix connect timeout config and add prefix for lookup query

---

flink-doris-connector/src/main/java/org/apache/doris/flink/sink/committer/DorisCommitter.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisStreamLoad.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisWriter.java

[Chore] Improve some log output

---

flink-doris-connector/src/main/java/org/apache/doris/flink/rest/RestService.java
flink-doris-connector/src/main/java/org/apache/doris/flink/rest/models/BackendV2.java
flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicOutputFormat.java
flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisStreamLoad.java

And timeout config and retry straegy 

[Pick] And timeout config and retry straegy 

---

flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/CdcSchemaChange.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mongodb/serializer/MongoDBJsonDebeziumSchemaSerializer.java
flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mongodb/serializer/MongoJsonDebeziumSchemaChange.java

[Fix](cdc) Ignore when mongodb schema change fails

---

flink-doris-connector/src/main/java/org/apache/doris/flink/sink/schema/SQLParserSchemaManager.java
flink-doris-connector/src/test/java/org/apache/doris/flink/sink/schema/SQLParserSchemaManagerTest.java

Fix sql_parse schema table annotation and field type parsing inaccuracies
Issue Number: close #538 

[Fix] Fix sql_parse schema table annotation and field type parsing inaccuracies

---

flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSink.java
flink-doris-connector/src/test/java/org/apache/doris/flink/sink/DorisSinkITCase.java

Support insert overwrite
Process: first truncate table, then write

[Feature] Support insert overwrite

---

NOTICE.txt

[Chore] update notice for 2025

---

flink-doris-connector/src/main/java/org/apache/doris/flink/sink/batch/DorisBatchStreamLoad.java

Issue Number: close #554
`dorisBatchStreamLoad.bufferMap`  get/remove operation add read-write lock.

add buffer-map read-write-lock

---

flink-doris-connector/src/main/java/org/apache/doris/flink/sink/HttpUtil.java

Because this pr https://github.com/apache/doris-flink-connector/pull/522 sets the httpclient configuration to readTimeout, but here is the http client configuration of streaml oad, which may be much longer than the default value of 60 seconds, causing the previous user configuration to fail to run.
So temporarily revert to the previous configuration, and it needs to be changed to a configurable one in the future …

[Fix] remove the socket timeout configuration of httpclient

---

flink-doris-connector/pom.xml

update flink doris connector version

update flink doris connector version

---

tools/releasing/create_release_branch.sh
tools/releasing/create_source_release.sh
tools/releasing/deploy_staging_jars.sh
tools/releasing/update_branch_version.sh

[Chore] Add release scipts

---

flink-doris-connector/pom.xml
flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/doris/DataModel.java
flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisReadOptions.java
flink-doris-connector/src/main/java/org/apache/doris/flink/lookup/Worker.java
flink-doris-connector/src/main/java/org/apache/doris/flink/serialization/RowBatch.java
flink-doris-connector/src/test/java/org/apache/doris/flink/container/AbstractContainerTestBase.java
flink-doris-connector/src/test/java/org/apache/doris/flink/container/AbstractITCaseService.java
flink-doris-connector/src/test/java/org/apache/doris/flink/container/ContainerUtils.java
flink-doris-connector/src/test/java/org/apache/doris/flink/container/e2e/Doris2DorisE2ECase.java
flink-doris-connector/src/test/java/org/apache/doris/flink/container/instance/ContainerService.java
flink-doris-connector/src/test/java/org/apache/doris/flink/container/instance/DorisContainer.java
flink-doris-connector/src/test/java/org/apache/doris/flink/lookup/DorisLookupTableITCase.java
flink-doris-connector/src/test/java/org/apache/doris/flink/sink/DorisSinkFailoverITCase.java
flink-doris-connector/src/test/java/org/apache/doris/flink/sink/DorisSinkITCase.java
flink-doris-connector/src/test/java/org/apache/doris/flink/source/DorisSourceITCase.java
flink-doris-connector/src/test/java/org/apache/doris/flink/utils/MockSource.java
flink-doris-connector/src/test/resources/container/e2e/doris2doris/test_doris2doris_sink_test_tbl.sql
flink-doris-connector/src/test/resources/container/e2e/doris2doris/test_doris2doris_source_test_tbl.sql
flink-doris-connector/src/test/resources/container/e2e/mysql2doris/testMySQL2Doris.txt
flink-doris-connector/src/test/resources/docker/doris/be.conf
flink-doris-connector/src/test/resources/docker/doris/fe.conf

**1. DorisSource**
- Add DorisSource case for arrowflight query and dup,uniq(mor/mow),agg model
**2. LookupJoin**
- Add lookup join case to test cache and async
**3. DorisSink**
- Add DorisSink case for  dup,uniq(mor/mow),agg model
Added exception cases:
- Streamload failure caused by injection, causing task restart
- Failure of snapshotState phase of checkpoint controlled by program, causing task restart
- Task restart caused by random container restart
**4. Other**
- Add be.conf fe.conf to customize the configuration of doris
- Optimize code: arrowflight adds validation and puts the lookup join query in front
6. Has unit tests been added: (Yes/No/No Need)
7. Has document been added or modified: (Yes/No/No Need)
8. Does it …

[Improve](case) add itcase for dorissource , dorissink and lookup join

---

flink-doris-connector/src/main/java/org/apache/doris/flink/sink/batch/DorisBatchStreamLoad.java

add the interval between retries in batch mode

[improve] add the interval between retries in batch mode

---

flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/JsonDebeziumSchemaChange.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/JsonDebeziumSchemaChangeImplV2.java
flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/SQLParserSchemaChange.java
flink-doris-connector/src/test/java/org/apache/doris/flink/container/e2e/Mysql2DorisE2ECase.java
flink-doris-connector/src/test/java/org/apache/doris/flink/lookup/DorisLookupTableITCase.java
flink-doris-connector/src/test/resources/container/e2e/mysql2doris/testMySQL2Doris.txt
flink-doris-connector/src/test/resources/container/e2e/mysql2doris/testMySQL2Doris_init.sql

1. Added rename operation
2. Added --table-prefix and --table-suffix
3. Added excluding-table
4. Added some option configurations for lookup join
5. Deprecated JsonDebeziumSchemaChangeImplV2 , Recommend use SQLParserSchemaChange.
6. Has unit tests been added: (Yes/No/No Need)
7. Has document been added or modified: (Yes/No/No Need)
8. Does it need to update dependencies: (Yes/No)
9. Are there any changes that cannot be rolled back: (Yes/No)

[Improve] add test case for cdc sync 
