- .github/workflows/build-extension.yml
- flink-doris-connector/build.sh
Add "--tag" option so that when we can build from a tag.
Because in tag, the flink and scala version is deterministic and does not need to be specified.
3. Has document been added or modified: (No)
The doc will be modified in apache/incubator-doris
> [chore] Modify the build.sh script

- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/GenericDorisSinkFunction.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSink.java
Issue Number: close 
flink写doris是批量写入，用户设置条数为1000条时，才flush，假如写入500条时，程序正好做checkpoint成功了，kafka的offset做了相应的commit，后面500条过来后，未做checkpoint，但此时doris服务器出了问题，导致flush报错，flink的task重启，重新从上次checkpoint commit的offset消费kafka，导致前面500条数据出现丢失情况
3. Has document been added or modified: (No)
> When doing checkpoint, write cache data to doris to prevent loss

- flink-doris-connector/src/main/java/org/apache/doris/flink/rest/RestService.java
目前，使用 flink-doris-connector 写入 Doris ，当配置了多个 Doris FE 节点的前提下， 内部通过 FE 节点请求到 BE 时会随机选择其中一个 FE 提交 http 请求 BE 节点地址；在生产环境中，由于机器原因或者是版本升级需要滚动重启 FE 服务时，由于某个 FE 服务暂时不可用，可能会引起 flink 作业异常退出；
为了降低集群变更或偶发异常影响实时流稳定，考虑通过对所有配置的  Doris FE 节点发送 http 请求查询 Doris BE。
Currently, when Flink-doris-Connetor writes Doris, it will queries Doris FE node through one of the Doris BE nodes randomly. It may causing job failures when one of Doris BE node in cluster is out of service. For example, sometime  machine has problem and need to restart or admin need to Actively restart service In the process of upgrading the version
5. Are there …
> [feature]Supports traversal of Doris FE nodes when searching for Doris BE

- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisExecutionOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicOutputFormat.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableFactory.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/DorisSourceSinkExample.java
目前，dorisSink 刷入 batch 的时机依赖 "batchSize" 和 "batchIntervalMs"，一般情形下是能够符合预期的；但是当数据源流量或者单条消息数据量极大时，可能会造成单个 batch 的数据很大，进而会导致数据刷入 doris 时长时间阻塞影响实时性能，甚至请求 BE 超时无法正常写入的问题。
出于上述原因，提供依据 "maxBatchBytes" 刷 batch 到 doris 中，修改点：
* 类 `DorisExecutionOptions`: 增加一个可配置选项 `maxBatchBytes`
* 类 `DorisDynamicOutputFormat`: 估计当前 batch 的数据量 `batchBytes` 达到阈值 `maxBatchBytes` 时，刷入 doris。
> [improvement] (before 1.13)Support set max bytes in each batch to avoid congestion

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/DorisSink.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisStreamLoad.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSink.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/DorisSinkExample.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/DorisSinkSQLExample.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/DorisSourceSinkExample.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/TestDorisStreamLoad.java
1. For stream load with json format，support read_json_by_line instead of strip_outer_array
2.  Remove non empty check for dorisReadOptions
4. Has unit tests been added: (Yes)
5. Has document been added or modified: (No Need)
6. Does it need to update dependencies: (No)
7. Are there any changes that cannot be rolled back: (No)
> json load by line

- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisReadOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSource.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisRowDataInputFormat.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/DorisSourceExample.java
Issue Number: close #28 
1.When the number of schemas of flink is inconsistent with the number of doris schemas, an error will be reported, especially when there are hidden columns in doris
2. deserialize has npe bug
> [Bug] fix flink schema and doris schema column not match

- flink-doris-connector/src/main/java/org/apache/doris/flink/deserialization/converter/DorisRowConverter.java
when use wrap, such as Integer, BigInteger appears null, it will be npe.
> FIX: fix wrap null

- README.md
The link to the website is broken. This PR fixes it.
The link to the website is broken. This PR fixes it.
1. Does it affect the original behavior: ni
2. Has unit tests been added: ni
3. Has document been added or modified: no
4. Does it need to update dependencies: no
5. Are there any changes that cannot be rolled back: no
> [docs] Fix broken link for doris connector docs

- flink-doris-connector/build.sh
1.add tips for Mac OS users in case meeting getopt error
> [Fix]add tips for Mac OS users in case meeting getopt error

- README.md
- flink-doris-connector/build.sh
- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/DorisCatalog.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/datastream/DorisSourceFunction.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/rest/RestService.java
Since [flink client](https://mvnrepository.com/artifact/org.apache.flink/flink-clients) changed groupId format, we may not build current project using 1.14 and below version.
I think it's better to change README.md to the 1.15 version.
2. Has unit tests been added: No Need
3. Has document been added or modified: Yes
> [docs] update readme.md flink version

- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisExecutionOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisLookupOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisConfigOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableFactory.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSource.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisRowDataLookupFunction.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/table/DorisRowDataLookupFunctionTest.java
At present, the data of the flink stream join doris table is to read the doris table into the memory at one time and join it, such as kafka join doris. This makes it impossible to read the newly added data of the doris table.
Therefore, lookup join is supported on the flink doris connector. The principle is to search in doris in real time according to the data in the fact stream.
tips:
For query performance, the cache setting is supported, which is disabled by default.
`lookup.cache.max-rows` //The maximum row of the cache
`lookup.cache.ttl`.            //cache's ttl
`lookup.max-retries`.      //The maximum number of retries to read doris
example:
```sql
CREATE TABLE fact_table (
`id` BIGINT,
`name` STRING,
`city` STRING,
`process_time` as proctime()
) WITH ( …
```
> [Feature] Support flink table lookup join

- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/DorisCatalogFactory.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisConfigOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableFactory.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSink.java
Support 'sink.parallelism' configuration 
3. Has document been added or modified: (Yes)
Support sink parallelism based on FLIP-146 
https://cwiki.apache.org/confluence/display/FLINK/FLIP-146%3A+Improve+new+TableSource+and+TableSink+interfaces
> [Feature] Support 'sink.parallelism' configuration

- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisConnectionOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisLookupOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/connection/JdbcConnectionProvider.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/connection/SimpleJdbcConnectionProvider.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/deserialization/converter/DorisRowConverter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/lookup/DorisJdbcLookupReader.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/lookup/DorisLookupReader.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/lookup/ExecutionPool.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/lookup/Get.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/lookup/GetAction.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/lookup/LookupSchema.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/lookup/Record.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/lookup/RecordKey.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/lookup/Worker.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisConfigOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableFactory.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSource.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisRowDataAsyncLookupFunction.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisRowDataJdbcLookupFunction.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/lookup/LookupJoinExample.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/lookup/RecordTest.java
The current lookup join #61  is based on thrfit reading data. After each piece of data comes, point query doris once.
When the amount of data is too large, the point query is too high, causing the QPS and CPU to be too high.
At the same time, it will cause Flink's data back pressure, resulting in data delay.
**Improvements:**
1. **Modify the query method to JDBC**. it makes easier to implement asynchronous and batch, and you can see monitoring indicators such as QPS and latency from Doris' monitoring, and know more clearly the execution status of the lookup operator
2. **Save batch to query**. Concatenate multiple query conditions into an union all statement, similar to `select a from tbl where (a=1) union all select a from tbl (a=2)`. This is a one-time query.
3. **Support asynchronous …
> [improve] improve lookup join to async and batch

- flink-doris-connector/src/main/java/org/apache/doris/flink/rest/RestService.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/rest/models/BackendV2.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisStreamLoad.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisWriter.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/TestDorisWriter.java
The current implementation is to always send a StreamLoad request to a coordinator BE, which may cause a certain BE to be overloaded.
Improvement: re-rotate every time Checkpoint selects the available be to initiate a streamload request
> [Improvement] dynamic refresh backend on each once checkpoint

- .github/workflows/build-extension.yml
- .mvn/wrapper/MavenWrapperDownloader.java
- .mvn/wrapper/maven-wrapper.properties
- env.sh
- flink-doris-connector/build.sh
- flink-doris-connector/pom.xml
- mvnw
Issue Number: close #114
Currently, in the build.sh script. env checks such as thrift, java, maven, etc., needs to be optimized. 
1. thrift needs to verify the version is 0.13.0
2. mvnw support(if not install maven)
3. check java env need to improvement
4. release process need to replace versions, see [doc](https://doris.apache.org/zh-CN/community/release-and-verify/release-doris-connectors#2-%E5%8F%91%E5%B8%83%E5%88%B0-maven-staging)，this steps can be improved
1. Does it affect the original behavior: I Don't know
2. Has unit tests been added: No
3. Has document been added or modified: No …
> [Enhancement] build project improvement

- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisRowDataAsyncLookupFunction.java
when cache open and lookup join is failed
> [lookup](cache)fix lookup join when cache open

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisWriter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/LabelGenerator.java
1. Currently, a streamload long link is opened during each checkpoint, even if there is no data during the entire checkpoint period
Optimized to establish a connection  if there has data
2. When 2pc is not enabled, the splicing of the label is changed to uuid
> [improve] reduce streamload connection

- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/DorisCatalog.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/DorisCatalogFactory.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/DorisCatalogOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/DorisTypeMapper.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/doris/DorisSystem.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/exception/DorisSystemException.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/catalog/CatalogTest.java
In FlinkCatalog, methods such as create table and create database are supported.
The current table defaults to the UNIQ model, the primary key is the key of the doris table and the bucket key, and the bucket is auto
```
CREATE CATALOG doris_catalog WITH(
> 'type' = 'doris',
> 'default-database' = 'db5',
> 'username' = 'root',
> 'password' = '',
> 'fenodes' = 'xxxx:8234',
> 'jdbc-url' = 'jdbc:mysql://xxx:9234',
> 'sink.label-prefix' = 'labelxxx'
> )
[INFO] Execute statement succeed.
Flink SQL> use catalog doris_catalog;
[INFO] Execute statement succeed.
Flink SQL> CREATE TABLE `doris_catalog`.`db5`.`t_all_types` (
>   `id` VARCHAR(16),
>   `c_boolean` BOOLEAN,
>   `c_char` CHAR(1),
>   `c_date` DATE,
>   `c_datetime` TIMESTAMP(0),
>   `c_decimal` DECIMAL(10, 2),
>   `c_double` DOUBLE,
> …
```
> support flink catalog create table

- flink-doris-connector/src/main/java/org/apache/doris/flink/connection/SimpleJdbcConnectionProvider.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/lookup/DorisJdbcLookupReader.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/lookup/DorisLookupReader.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/lookup/ExecutionPool.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/lookup/Worker.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisRowDataAsyncLookupFunction.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisRowDataJdbcLookupFunction.java
When flinkjob or a task is automatically restarted, the thread pool in the previous lookup task is not closed, resulting in a surge in threads
> [Fix] lookup join close executor service

- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisExecutionOptions.java
Add a builderDefaults() method which returns Builder in stead of DorisExecutionOptions. 
According to the Builder pattern, this method can not only configure the json format and reading json by line, but also configure other parameters that developers need to set.
3. Has document been added or modified: (No)
> [Improve]Optimize method for constructing builder object based on Builder pattern

- flink-doris-connector/src/main/java/org/apache/doris/flink/deserialization/DorisJsonDebeziumDeserializationSchema.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/JsonDebeziumSchemaSerializer.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/CdcTools.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mysql/MysqlDatabaseSync.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcMysqlSyncDatabaseCase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcOraclelSyncDatabaseCase.java
At present, when the mysql database sync to doris , there is a default value in the field, but the actual data is null, the data cannot maintain consistency.
Like: when mysql schema has a default value and the insertion is ` null `, the data synchronized to doris uses the default value.
```  sql
CREATE TABLE `test_sink` (
`id` int NOT NULL,
`name` varchar(50) DEFAULT 'test_default',
`age` int DEFAULT '10000',
PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
insert into test_sink (id,name,age) values(6, null, 666);
insert into test_sink (id,name,age) values(5, 'zhaoliu', null);
```
Configure  `--ignore-default-value`, the default value will not be synchronized, otherwise it will be synchronized.
1. Does it affect the …
> [Improve](mysqlSync)Add the configuration of whether to synchronize the default value

- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/doris/DorisSystem.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/SourceSchema.java
When the key is recognized as a string type, the table cannot be created.
So convert the mapping of key to varchar(65533)
> [improvement] update create table modify string key to varchar

- flink-doris-connector/pom.xml
- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/doris/FieldSchema.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/JsonDebeziumSchemaSerializer.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/SchemaChangeHelper.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/CdcTools.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/CDCSchemaChangeExample.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/TestJsonDebeziumSchemaSerializer.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcMysqlSyncDatabaseCase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcOraclelSyncDatabaseCase.java
The old schema change need to use regular expressions to match, resulting in comparison limitations.
The new schema change:
1. supports multi-column changes
2. support for synchronous defaults.
MySQL multi-table import enables new schema change only by configuring `--use-new-schema-change`, oracle does not currently support
4. Has unit tests been added: (Yes/No/No Need)
5. Has document been added or modified: (Yes/No/No Need)
6. Does it need to update dependencies: (Yes/No)
7. Are there any changes that cannot be rolled back: (Yes/No)
If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the …
> [Improve](schemaChange)schema change ddl supports multi-column changes, synchronous defaults

- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisExecutionOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/exception/DorisBatchLoadException.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/BackendUtil.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/batch/BatchRecordBuffer.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/batch/DorisBatchSink.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/batch/DorisBatchStreamLoad.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/batch/DorisBatchWriter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisWriter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisConfigOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableFactory.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSink.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/DorisSinkBatchExample.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/TestBackendUtil.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/batch/TestBatchRecordBuffer.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/TestDorisWriter.java
At present, the writing of Flink Connector can only rely on the writing of checkpoint.
Not very friendly to two scenarios:
1. Jobs that do not need to enable checkpoint
2. The ETL of Flink jobs is complicated, which makes the checkpoint very slow, but it does not want to affect the writing performance.
For these two situations, the batch write function is added:
Introduce parameters:
**sink.enable.batch-mode**:  Whether to enable batch write mode, default is false
**sink.flush.queue-size**:    Queue length for async stream load, default is 2
**sink.buffer-flush.max-rows**: The maximum number of flush items in each batch, the default is 5w
**sink.buffer-flush.max-bytes**: The maximum number of bytes flushed in each batch, the default is 10MB
**sink.buffer-flush.interval**: the flush …
> [Feature] add stream load batch write

- flink-doris-connector/pom.xml
- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisExecutionOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/JsonDebeziumSchemaSerializer.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisConfigOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableFactory.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSink.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/TestJsonDebeziumSchemaSerializer.java
In the CDC scenario, when the primary key of the upstream is inconsistent with that of the downstream, the update-before data needs to be passed to the downstream as deleted data, otherwise the data cannot be deleted. The default is to ignore, that is, perform upsert semantics.
> [Improve]add sink.ignore-update-before

- flink-doris-connector/pom.xml
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/JsonDebeziumSchemaSerializer.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/CdcTools.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/postgres/PostgresDatabaseSync.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/postgres/PostgresDateConverter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/postgres/PostgresSchema.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/postgres/PostgresType.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcPostgresSyncDatabaseCase.java
1. Add Postgresql whole database synchronization, the specific process is the same as #141.
The example is as follows:
```shell
-Dexecution.checkpointing.interval=10s\
-Dparallelism.default=1\
-c org.apache.doris.flink.tools.cdc.CdcTools\
./lib/flink-doris-connector-1.16-1.5.0-SNAPSHOT.jar\
postgres-sync-database \
--database db1\
--postgres-conf hostname=127.0.0.1 \
--postgres-conf port=5432 \
--postgres-conf username=postgres \
--postgres-conf password="123456" \
--postgres-conf database-name=postgres \
--postgres-conf schema-name=public \
--postgres-conf slot.name=test \
--postgres-conf decoding.plugin.name=pgoutput \
--including-tables "tbl1|tbl2" \
--sink-conf fenodes=127.0.0.1:8030 \
--sink-conf username=root \
--sink-conf password=\
--sink-conf …
```
> [Feature] add postgresql cdc

- flink-doris-connector/pom.xml
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mysql/MysqlDatabaseSync.java
Issue Number: close #154 
Bump Flink CDC MySQL Connector version to 2.4.0
2. Has unit tests been added: No
3. Has document been added or modified: No
4. Does it need to update dependencies: Yes
I carefully tested and have re-deployed half of our online streaming ETL jobs using the newest Flink CDC 2.4 framework, which look good so far, except this issue: https://github.com/ververica/flink-cdc-connectors/issues/2243
The new feature of mysql connector that allows our job to automatically close idle readers has some problems when a single job syncs multiple tables and later we add new tables in sync list.
However, this feature looks good when you just want to sync single table. It will …
> [Improvement] Bump Flink CDC MySQL Connector version to 2.4.0 (#154)

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/batch/DorisBatchStreamLoad.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/DorisSinkBatchExample.java
In batch sink scenario, when flush(true) is called and buffer is null, waitAsyncLoadFinish() will not be triggered. Modify this part of logic to ensure that waitAsyncLoadFinish() must be triggered
> [fix] fix batch sink flush lost batch

- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mysql/MysqlDatabaseSync.java
1. Multi-table synchronization, increase the parameters of batch saving
2. Compatible with flinkcdcmysql2.3.0, first remove the property of SCAN_INCREMENTAL_CLOSE_IDLE_READER_ENABLED
> [fix] add batch option

- flink-doris-connector/pom.xml
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/CdcTools.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/postgres/PostgresType.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/sqlserver/SqlServerDatabaseSync.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/sqlserver/SqlServerDateConverter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/sqlserver/SqlServerSchema.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/sqlserver/SqlServerType.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcSqlServerSyncDatabaseCase.java
1. Add SqlServer database synchronization, the specific process is the same as #141.
The example is as follows:
```shell
-Dexecution.checkpointing.interval=10s\
-Dparallelism.default=1\
-c org.apache.doris.flink.tools.cdc.CdcTools\
./lib/flink-doris-connector-1.16-1.5.0-SNAPSHOT.jar\
sqlserver-sync-database \
--database db1\
--sqlserver-conf hostname=127.0.0.1 \
--sqlserver-conf port=1433 \
--sqlserver-conf username=sa \
--sqlserver-conf password="123456" \
--sqlserver-conf database-name=CDC_DB \
--sqlserver-conf schema-name=dbo \
--including-tables "tbl1|tbl2" \
--sink-conf fenodes=127.0.0.1:8030 \
--sink-conf username=root \
--sink-conf password=\
--sink-conf jdbc-url=jdbc:mysql://127.0.0.1:9030 \
--sink-conf sink.label-prefix=label \
--sink-conf sink.enable-2pc=false \ …
```
> [Feature] add sqlserver cdc

- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mysql/MysqlType.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/postgres/PostgresType.java
1. mysql char => doris varchar
2. pg array<T> => doris string, Compatible with doris 1.2
> [fix] fix type mapping with mysql and pg

- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mysql/MysqlDatabaseSync.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/sqlserver/SqlServerType.java
add mysql column key column:
`--mysql-conf scan.incremental.snapshot.chunk.key-column = db.tbl1:col1,db.tbl2:col2`
mysqlcdc version must be greater than 2.4
> [mysql] add mysql chunk column options

- flink-doris-connector/pom.xml
- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisConnectionOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/BackendUtil.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/batch/DorisBatchStreamLoad.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/committer/DorisCommitter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisWriter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisConfigOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableFactory.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSource.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisRowDataInputFormat.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/DorisIntranetAccessSinkExample.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/committer/TestDorisCommitter.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcMysqlSyncDatabaseCase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcOraclelSyncDatabaseCase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcPostgresSyncDatabaseCase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcSqlServerSyncDatabaseCase.java
When the flink connector accesses DORIS, it parses out all surviving BE nodes according to the FE address filled in.
However, when the BE node is deployed, most of the internal network IP is filled in,so the BE node parsed by FE is the internal network IP. When flink is deployed on a non-intranet segment,the BE node will be inaccessible on the network.
In this pr, you can access the BE node on the intranet by directly configuring `DorisOptions.builder().setBenodes().build()`
, after you configure this parameter, Flink Connector will not parse all BE nodes through FE nodes.
4. Does it need to …
> [Improve]Added direct access to BE through the intranet

- flink-doris-connector/src/main/java/org/apache/doris/flink/lookup/ExecutionPool.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/oracle/OracleDatabaseSync.java
When include-tables has too many table names, and debezium incrementally reads, it will be judged based on `regexp_like`. When the regular length exceeds 512, an error will be reported, like `ORA-12733: regular expression too long`
> [fix](oracle) add oracle regexp like compatible

- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mysql/DateToStringConverter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mysql/MysqlDatabaseSync.java
fix mysql datetime missing millisecond digits
> [Fix](mysql) fix mysql datetime missing millisecond digits

- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/DorisCatalogFactory.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisExecutionOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/CacheRecordBuffer.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisStreamLoad.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisWriter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/RecordBuffer.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/RecordStream.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisConfigOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableFactory.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/TestCacheRecordBuffer.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/TestDorisStreamLoad.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/TestDorisWriter.java
another impl for pr 194(https://github.com/apache/doris-flink-connector/pull/184): 
support doris cache writer, which will cache data for cp; once the stream load fail, will abort the transaction and restart a new stream load with the cache data instead of restart the task.
If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you …
> [Feature](CacheWriter) doris sink support cache record buffer

- flink-doris-connector/src/main/java/org/apache/doris/flink/lookup/DorisJdbcLookupReader.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/lookup/Worker.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/lookup/RecordTest.java
The upstream sends a batch of data with the same key. When querying using union all, it will cause the same key and multiple duplicate values to appear in the resultRecordMap. When getting the value again, it will lead to repeated circular assignment, so the data of lookup join will increase.
> [bug](lookup) Fix the duplicate data problem that may be caused by lookup

- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/doris/DorisSystem.java
If there are single quotes in ddl statements, table creation fails
as shown below
> [fix] If there are single quotes in ddl statements, table creation fails

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/JsonDebeziumSchemaSerializer.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/oracle/OracleDatabaseSync.java
In some cases, the ddl statement passed by cdc will not be included in `historyRecord`, so it is compatible with this
> [improve] add ddl parse for debeziumSourcefunction 

- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisConnectionOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisExecutionOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/exception/ConnectedFailedException.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/rest/RestService.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/rest/models/BackendV2.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/DorisSink.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisConfigOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableFactory.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
1. When currently writing, the be list is obtained first, and then the streamload request is initiated to be in rotation. Add auto-redirect parameter to turn on fe automatic redirection
2. when writing uniq model, 2pc is closed by default (supports forced opening)
4. Has unit tests been added: (Yes/No/No Need)
5. Has document been added or modified: (Yes/No/No Need)
6. Does it need to update dependencies: (Yes/No)
7. Are there any changes that cannot be rolled back: (Yes/No)
> [improve] add auto redirect and uniq default open 2pc

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/batch/BatchRecordBuffer.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/batch/TestBatchRecordBuffer.java
When importing in batch mode, when a row of data is too large and is larger than the remaining buffer, insert will report an error.
> [bug] fix buffer memory grow bug

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/LabelGenerator.java
Currently, when 2pc is closed, the label will only splice the uuid without adding the ckid, which is inconvenient to locate the problem.
> [improve] add ckptid  in label when 2pc false

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/committer/DorisCommitter.java
In extreme cases, the status when commit fails will return unkown status, which will cause the logic of status.euqal(fail) to be true, which means the import is successful by default, but it actually fails, so some data will be lost.
> [improve] improve check commit response

- flink-doris-connector/src/main/java/org/apache/doris/flink/deserialization/converter/DorisRowConverter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/serialization/RowBatch.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/serialization/TestRowBatch.java
Support doris map, struct type reading and writing
```java
//doris create table
CREATE TABLE `simple_map2` (
`id` int(11) NULL,
`m` MAP<text,int(11)> NULL,
`s_info` STRUCT<s_id:int(11),s_name:text,s_address:text> NULL
) ENGINE=OLAP
DUPLICATE KEY(`id`)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(`id`) BUCKETS 1
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"is_being_synced" = "false",
"storage_format" = "V2",
"light_schema_change" = "true",
"disable_auto_compaction" = "false",
"enable_single_replica_compaction" = "false"
); 
//datagen->doris
tEnv.executeSql(
"CREATE TABLE doris_test (" +
"  id int,\n" +
"  task Map<String,int>,\n" +
"  buyer ROW<s_id int,s_name string, s_address string>\n" +
") " +
"WITH (\n" +
"  'connector' = 'datagen', \n" +
"  'number-of-rows' = '11' \n" + …
```
> [feature] support  struct and map type

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/DorisSink.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/committer/DorisCommitter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisStreamLoad.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisWriter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSink.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/committer/MockCommitRequest.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/committer/TestDorisCommitter.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/TestDorisWriter.java
The current implementation of dorissink is based on the sinkv1 version, which will be refactored into the sinkv2 version according to [FLIP-191](https://cwiki.apache.org/confluence/display/FLINK/FLIP-191%3A+Extend+unified+Sink+interface+to+support+small+file+compaction).
> [refactor] sink api refactor by FLIP-191

- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisExecutionOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/BackendUtil.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/committer/DorisCommitter.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/committer/TestDorisCommitter.java
1. Modify the number of retry times under datastream
2. Modify the problem of reducing the number of retry attempts once
3. Fix that retry does not take effect. Currently, DorisRunntimeException is thrown and IOException is captured.
> [improve] improve commit retry strategy

- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisExecutionOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/LoadConstants.java
If format=json is set but read_json_by_line is not set, record may not be written.
> [improve] change option default when format is json

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/JsonDebeziumSchemaSerializer.java
We fully consider that doing schema changes when there is no data in the table is a relatively low-frequency operation. The existing framework is compatible with this kind of operation and the changes are relatively large, so only the prompt log is added.
Related pr: https://github.com/apache/doris-flink-connector/pull/243
If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the …
> [fix]Add a log prompt to perform schame change table update when there is no data in the table

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/batch/DorisBatchWriter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisWriter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/DorisRecord.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/DorisRecordSerializer.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/JsonDebeziumSchemaSerializer.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/RecordWithMetaSerializer.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/RowDataSerializer.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/RowSerializer.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/SimpleStringSerializer.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/deserialization/convert/DorisRowConverterTest.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/TestJsonDebeziumSchemaSerializer.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/TestRowDataSerializer.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/TestRowSerializer.java
Currently, the return value of DorisRecordSerializer is Tuple2<db.table,value>, which can meet the needs of multiple tables, but is not conducive to expansion.
Therefore, a layer of DorisRecord is abstracted
> [Improve] Optimize the return value of DorisRecordSerializer

- flink-doris-connector/pom.xml
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/JsonDebeziumSchemaSerializer.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/CdcTools.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/ParsingProcessFunction.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/SourceSchema.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/TestJsonDebeziumSchemaSerializer.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcMysqlSyncDatabaseCase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcOraclelSyncDatabaseCase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcPostgresSyncDatabaseCase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcSqlServerSyncDatabaseCase.java
Currently, when synchronizing the entire database, a sink will be created for each table. When there are too many tables, Flink will have too many operators and there will be pressure when building the topology, so a single sink is used for synchronization. Can be enabled via option `--single-sink`
Other changes:
1. Upgrade cdc version to 2.4.2
2. Optimize some codes
4. Has unit tests been added: (Yes/No/No Need)
5. Has document been added or modified: (Yes/No/No Need)
6. Does it need to update dependencies: (Yes/No)
7. Are there any changes that cannot be rolled back: (Yes/No) …
> [Feature](CDC)Support database sync use single sink

- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/DorisTypeMapper.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/rest/RestService.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/schema/SchemaChangeManager.java
Flink varchar length max value is int, it may overflow after multiplying by 4
> [Bug] Fix type overflow bug

- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/doris/DorisSystem.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/exception/DorisSchemaChangeException.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/schema/SchemaChangeHelper.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/schema/SchemaChangeManager.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/JsonDebeziumSchemaSerializer.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/schema/SchemaManagerTest.java
Currently, when adding column in schemachange, if the column already exists, an error will be reported. Make a judgment. If the column already exists, then schemachange is still successful.
> [Improve] schema change idempotent with add and drop column

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisWriter.java
Issue Number: close #256
#224 Made a change to DorisWriterState without considering connector state compatibility, resulting in an upgrade to 1.5.0 error, So I wana to fix this.
> [Bug] Fix the state compatibility problem

- flink-doris-connector/src/main/java/org/apache/doris/flink/serialization/RowBatch.java
If the table model is a unique model and the __DORIS_DELETE_SIGN__ column is not specified in doris.read.field when reading, the error "Load Doris data failed, schema size of fetch data is wrong" will appear.
> [fix]fix Load Doris data failed, schema size of fetch data is wrong

- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/DorisTypeMapper.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mysql/MysqlType.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/TestJsonDebeziumSchemaSerializer.java
The length of char needs to be multiplied by 3 as a judgment
At the same time, modify the length of varchar to 3. If you need longer characters, you can use string instead.
Reference here: https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-reference/Data-Types/VARCHAR/
> [fix] improve char length proplem

- flink-doris-connector/pom.xml
- tools/maven/checkstyle.xml
- tools/maven/suppressions.xml
Related PR:
https://github.com/apache/doris-flink-connector/pull/269 
https://github.com/apache/doris-flink-connector/pull/272
https://github.com/apache/doris-flink-connector/pull/273
> [step4][Improve]Format suppressions files and pom files

- .github/workflows/run-e2ecase.yml
- flink-doris-connector/pom.xml
- flink-doris-connector/src/test/java/org/apache/doris/flink/DorisTestBase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/MySQLDorisE2ECase.java
Currently, flinkcdc is integrated into the connector.
Therefore, we need to add some end-to-end cases.
This PR adds the case of mysql2doris
Contains the following tests
1. Automatically create doris table
2. Schema change event synchronization
3. Synchronization of addition, deletion and modification events on mysql side
4. CDC multi-table synchronization
5. Has unit tests been added: (Yes/No/No Need)
6. Has document been added or modified: (Yes/No/No Need)
7. Does it need to update dependencies: (Yes/No)
8. Are there any changes that cannot be rolled back: (Yes/No)
If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by …
> [test](e2ecase) add mysql2doris e2ecase

- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/sqlserver/SqlServerType.java
Issue Number: close [#Doris28408](https://github.com/apache/doris/issues/28408)
> [improve](cdc-tool) support sqlserver uniqueidentifier type

- .github/workflows/run-e2ecase-12.yml
- .github/workflows/run-e2ecase-20.yml
- .github/workflows/run-itcase-12.yml
- .github/workflows/run-itcase-20.yml
- flink-doris-connector/src/test/java/org/apache/doris/flink/DorisTestBase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/MySQLDorisE2ECase.java
Optimize doris container log print
> [test](e2ecase) Optimize doris container log print

- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/DorisCatalog.java
When catalog does not fill in fenodes, the query fe will be displayed. Before 1.2, the IP was returned, and after 2.0, the Host was returned, so it is compatible.
> [Fix] catalog queries fenodes compatibility

- .github/workflows/build-extension.yml
- flink-doris-connector/build.sh
- flink-doris-connector/pom.xml
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/batch/BatchRecordBuffer.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/batch/DorisBatchStreamLoad.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/batch/DorisBatchWriter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisStreamLoad.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisWriter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/LoadConstants.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/DorisRecord.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/DorisRecordSerializer.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/RowDataSerializer.java
- flink-doris-connector/src/main/java/org/apache/flink/table/runtime/arrow/serializers/ArrowSerializer.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/TestRowDataSerializer.java
> [feature]add arrow type for streamload

- .gitignore
The connector jar file was unversioned after building, we should add the dist dir to `.gitignore`.
> [fix] Add dist dir to gitignore

- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/CdcTools.java
close #260
Return a new map instead of null when the key-value parameters are invalid or not specified.
1. Does it affect the original behavior: (No
> [fix] Fix NPE when getting map params

- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/DorisCatalog.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/DorisTypeMapper.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/doris/DorisType.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/catalog/CatalogExample.java
When accessing the table through flink catalog, array, map, json and other types will report errors.
[ERROR] Could not execute SQL statement. Reason:
java.lang.UnsupportedOperationException: Doesn't support Doris type 'ARRAY' on column 'c_column'
> [catalog] add array map json type for flink catalog

- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/doris/DorisSystem.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/doris/TableSchema.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/CdcTools.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/SourceSchema.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcMysqlSyncDatabaseCase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcOraclelSyncDatabaseCase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcPostgresSyncDatabaseCase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcSqlServerSyncDatabaseCase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/DatabaseSyncTest.java
The `--table-conf  table-buckets = table1:num1,table2:num2,tbl.*:num3,.*:num4` option can be used to specify the number of buckets for different tables when synchronizing databases and specifying buckets. Therefore, the number of buckets for `table1` and `table2` is represented by `num1`and `num2` respectively. All buckets prefixed with `tbl1` are assigned the value of `num3`, while all other buckets are assigned the value of `num4`.
```sql
-Dexecution.checkpointing.interval=10s \
-Dparallelism.default=1 \
-c org.apache.doris.flink.tools.cdc.CdcTools \
lib/flink-doris-connector-1.17-1.5.0-SNAPSHOT.jar \
mysql-sync-database \
--database student_cdc \
--mysql-conf hostname=127.0.0.1 \
--mysql-conf port=3306 \
--mysql-conf username=root \
--mysql-conf password=123456 \ …
```
> [feature][cdc] specify bucket when synchronizing database

- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/CdcTools.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/DorisTestBase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/MySQLDorisE2ECase.java
Added printing parameter log to facilitate positioning, and moved parameter verification forward
> [log](improve)Add printing parameters and move the verification forward

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/JsonDebeziumSchemaSerializer.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/JsonDebeziumChangeContext.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/JsonDebeziumSchemaChangeImplV2.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/TestJsonDebeziumDataChange.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/TestJsonDebeziumSchemaChangeImpl.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/TestJsonDebeziumSchemaChangeImplV2.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/MySQLDorisE2ECase.java
Currently, when single-sink is enabled and CDC automatically creates a table, it cannot automatically obtain the suffix and suffix.
> [fix](cdc) single sink add tableprefix and tablesuffix

- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisConfigOptions.java
Automatic redirection is turned on by default when streamload is writing.
> [Improve](sink) deafult open auto redirect

- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/doris/DorisSystem.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/schema/SchemaChangeHelper.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/JsonDebeziumSchemaChangeImplV2.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/SourceSchema.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/schema/SchemaChangeHelperTest.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/schema/SchemaManagerTest.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/TestJsonDebeziumSchemaChangeImplV2.java
fix：
1. Currently, creating a table does not support default value.
2. Currently, when the schema changes, quotation marks will not be added to the default value.
> [Improve](cdc) Fix default value in cdc

- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisExecutionOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/DorisSink.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/batch/DorisBatchSink.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/batch/DorisBatchWriter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisAbstractWriter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisWriter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/WriteMode.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisConfigOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableFactory.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSink.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/DorisSinkBatchExample.java
Currently, this PR implements batch writing of streamload, https://github.com/apache/doris-flink-connector/pull/168
However, at the datastream usage level, different sinks pose relatively large barriers to use for users, so we will unify them here.
Abstract DorisAbstractWriter and use parameters `sink.write-mode` to distinguish different writes
If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you …
> [improve] Add DorisAbstractWriter, Unify DorisSink and DorisBatchSink

- flink-doris-connector/src/main/java/org/apache/doris/flink/rest/RestService.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/BackendUtil.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/schema/SchemaManagerTest.java
Check the status of fe and be before connect.
> [improve] Check the status of fe and be before connect

- flink-doris-connector/src/main/java/org/apache/doris/flink/exception/CopyLoadException.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/DorisAbstractCommittable.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/DorisSink.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/HttpPutBuilder.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/HttpUtil.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/ResponseUtil.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/copy/BackoffAndRetryUtils.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/copy/BatchStageLoad.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/copy/CopyCommittableSerializer.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/copy/CopySQLBuilder.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/copy/DorisCopyCommittable.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/copy/DorisCopyCommitter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/copy/DorisCopyWriter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/copy/HttpPostBuilder.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/copy/models/BaseResponse.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/copy/models/CopyIntoResp.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/LabelGenerator.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/copy/TestDorisCopyCommitter.java
Currently `sink.write-mode` supports `stream_load`, and `stream_load_batch` is used for streamload import.
Now the import method of `copy` load is added to adapt to the scenario of Doris storage and calculation separation.
The import is divided into two steps:
1. First upload the data to object storage.
2. Then load the data on the object storage into Doris.
This import method is usually used for synchronization across vpc scenarios (flink cluster and doris cluster).
If this is a relatively large or complex change, …
> [Feature](sink) add copy mode to sink

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/JsonDebeziumSchemaSerializer.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/JsonDebeziumChangeUtils.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/JsonDebeziumDataChange.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/JsonDebeziumSchemaChange.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/JsonDebeziumSchemaChangeImpl.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/JsonDebeziumSchemaChangeImplV2.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/TestJsonDebeziumDataChange.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/TestJsonDebeziumSchemaChangeImplV2.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcMysqlSyncDatabaseCase.java
When the `singleSink` parameter is turned on, multiple tables use the same sink task, and multiple tables also share the same `originFieldSchemaMap`. However, `originFieldSchemaMap` does not differentiate based on the table name, resulting in incorrect results when the schema is changed.
If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you …
> [fix]Fix multi-table sink, schema change result is incorrect

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/BackendUtil.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/JsonDebeziumSchemaSerializer.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/CdcTools.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
change use-new-schema-change config deafult to true
> [improve]change use-new-schema-change config deafult to true

- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/doris/TableSchema.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/oracle/OracleDatabaseSync.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/sqlserver/SqlServerDatabaseSync.java
In Oracle , the table names to contain special characters such as /, #, $, etc.. However, Doris does not support tables with these characters.
> [fix](cdc) add Oracle table name validation

- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/oracle/OracleDatabaseSync.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/DatabaseSyncTest.java
Convert the value of table.include.list from `db.tbl_1|db.tbl2 to (db).(tbl_1|tbl_2)`
This is very useful during Oracle synchronization, because debezium is limited by regex_like function characters when reading from Oracle.
> [improve] oracle cdc regex improve

- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisExecutionOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/DorisSink.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/committer/DorisCommitter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisConfigOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableFactory.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/committer/TestDorisCommitter.java
Normally, in 2pc, commit cannot fail, otherwise it will cause data loss.
But sometimes, when resuming a task from checkpoint, the txnid recorded in the checkpoint may have expired. At this time, an error txn not found will be reported, including some other unexpected errors.
At this time, the offset of the source saved by ckpt cannot be used. If the txn is submitted successfully, the first commit failure can be tolerated.
Therefore, the parameter `sink.ignore-commit-error` is added. 
Usually used in 2pc failure recovery, the default is false. If the checkpoint encounters an unrecoverable scenario (such as txn not found), you can temporarily turn on the recovery, and then close the configuration after the checkpoint is normal. …
> [Improvement] add option ignore commit error

- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/ConfigurationOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisConfigOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableFactory.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
Currently, some Flink parameters are not standardized, such as doris.request.connect.timeout.ms, etc.
Therefore, the time type is uniformly modified to Duration, and the memory size type is uniformly modified to MemorySize
> [Improve] standardize Flink parameters

- .github/workflows/run-e2ecase.yml
- .github/workflows/run-itcase.yml
- flink-doris-connector/src/test/java/org/apache/doris/flink/DorisTestBase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/MySQLDorisE2ECase.java
The current case will start multiple doris container images, which can be optimized to a single instance image to make it run faster.
refer to [manual_lifecycle_control](https://java.testcontainers.org/test_framework_integration/manual_lifecycle_control/)
> [improve] make doris container singleton

- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/DorisCatalogFactory.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/rest/RestService.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisConfigOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableFactory.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSource.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisExpressionVisitor.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/table/DorisDynamicTableSourceTest.java
Background: Currently, DorisSource can only implement FilterPushDown and ProjectionPushDown through read.fields and filter.query, but cannot implement pushdown for the where that comes with FlinkSQL.
> [Improvement] SupportsFilterPushDown and ProjectionPushDown in DorisSource

- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/ConfigurationOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/serialization/RowBatch.java
In some scenarios, such as when reading a large amount of data, the default parameters of the Connector may cause failure, such as timeout, memory limit, etc.
So here we improve the default parameter values to ensure that they can be used out of the box as much as possible.
> [Improvement] change default config

- flink-doris-connector/src/main/java/org/apache/doris/flink/serialization/RowBatch.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/serialization/TestRowBatch.java
Compatible with arrow serialization type modifications for date/datetime in the following pr:
https://github.com/apache/doris/pull/32281
> [improve]Compatible with reading doris date/datetime arrow type modification

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/CdcDataChange.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/JsonDebeziumSchemaChangeImplV2.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/TestJsonDebeziumSchemaChangeImplV2.java
In MySQL 5.7.x, renaming a column using the syntax `RENAME COLUMN old_column_name TO new_column_name` is not supported. However, you can change the column name using the syntax `CHANGE COLUMN old_column new_column datatype`. Therefore, we can resolve this issue by adding compatibility for the 'CHANGE old_column new_column' syntax in MySQL. …
> [improve](cdc) support changing column names using the 'CHANGE' statement

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisStreamLoad.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/TestDorisStreamLoad.java
Currently, if an error occurs during abort, an exception will not be thrown. The connector will consider the abort to be successful, resulting in an error that the label has been used during the next streamload, such as
```java
21:39:51,176 INFO  org.apache.doris.flink.sink.writer.DorisStreamLoad           [Sink: Writer -> Sink: Committer (1/1)#0]  - table test_flink_a stream load stopped for 6bff8cfe-8ad5-4069-8588-c47221936ae9_test_test_flink_a_0_1 on host 10.16.10.6:28737
21:39:51,177 INFO  org.apache.doris.flink.sink.writer.DorisStreamLoad           [Sink: Writer -> Sink: Committer (1/1)#0]  - load Result {
"TxnId": -1,
"Label": "6bff8cfe-8ad5-4069-8588-c47221936ae9_test_test_flink_a_0_1",
"Comment": "",
"TwoPhaseCommit": "true",
"Status": "Label Already …
```
> [bug] Fix abort failure bug

- flink-doris-connector/src/main/java/org/apache/doris/flink/exception/LabelAlreadyExistsException.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/rest/models/RespContent.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/ResponseUtil.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/batch/RecordWithMeta.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisStreamLoad.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisWriter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/LabelGenerator.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/TestResponseUtil.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/TestDorisStreamLoad.java
1. In the case of writing to multiple tables, such as tables A, B, and C, if tables D and E are added during the period (there is no streamloader for this table in the previous Checkpoint), in the precommit phase, if table D succeeds but table E fails, this will retry from the last Checkpoint, but there is no streamloader of table D in the last checkpoint, so the txn of table D that has been successfully precommitted cannot be aborted, and the error **LabelAlreadyExists** will be reported next time
2. In the scenario of writing to multiple tables, if the sink is multi-concurrent,
At this time, the A thread reports an error, and the B thread Http request has ended, and the txnid of successful precommit has not been obtained. However, when jobmanager tries to cancel …
> [improvement] fix some successfully precommitted cannot be aborted lead to LabelAlreadyExists

- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisExecutionOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisStreamLoad.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisWriter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisConfigOptions.java
1. When there are multiple tables, there is no need to create threads
2. The checker thread is closed by default
> [Chore] disable checker thread default

- flink-doris-connector/src/main/java/org/apache/doris/flink/serialization/RowBatch.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/serialization/TestRowBatch.java
In the previous PR (https://github.com/apache/doris-flink-connector/pull/365), we added support for reading both IPv4 and IPv6 addresses starting from Doris 2.1.1. In this PR, we further enhance the functionality to support reading IPv4 addresses since version 2.1.0.
If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what …
> [improve] support  read ipv4 in Doris 2.1.0

- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisConfigOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableFactory.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSource.java
1. #348 Implemented filter pushdown and projection pushdown
But in some scenarios, flinksql cannot push down expressions
for example
```
insert into kafka_sink 
select * from  doris_source 
where  sh_pick_dt >=  DATE_FORMAT(TIMESTAMPADD(DAY,-9, CURRENT_TIMESTAMP),'yyyy-MM-dd');
```
2. At the same time, many users who upgraded from the previous version cannot upgrade smoothly, so they are compatible with …
> [Improve]Compatible with previous filter query options

- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/DorisTypeMapper.java
> [fix] Fix the bug that the `DorisTypeMapper` datetime type will lose precision when converted to flink type

- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSource.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisExpressionVisitor.java
Issue [376](https://github.com/apache/doris-flink-connector/issues/376): close #xxx
> [fix](source) fix  projection and function pushdown not functioning correctly

- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
When dealing with multiple databases in MySQL, it's common to have tables with identical schemas spread across different databases. If you try to synchronize these databases to Doris using the provided shell script, 
```
-Dexecution.checkpointing.interval=10s \
-Dparallelism.default=1 \
-c org.apache.doris.flink.tools.cdc.CdcTools \
lib/flink-doris-connector-1.17-1.6.0.jar \
mysql-sync-database  \
--mysql-conf hostname=127.0.0.1 \
--mysql-conf port=3306 \
--mysql-conf username=root \
--mysql-conf password=123456 \
--mysql-conf database-name="multi.*" \
--sink-conf fenodes=127.0.0.1:8030 \
--sink-conf username=root \
--sink-conf password=123456 \
--sink-conf jdbc-url=jdbc:mysql://127.0.0.1:9030 \
--sink-conf sink.label-prefix=label \
--table-conf replication_num=1 
```
you …
> [fix][cdc] fix uid conflicts during multi-database synchronization.

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/BackendUtil.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisWriter.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/TestBackendUtil.java
For example, consider multiple BEs in Apache Doris. The load is not balanced during concurrent imports. At the same checkpoint, multiple stream load tasks are directed to the same BE, causing server pressure on the backends because the `Pos` variables are the same within the checkpoint. To address this, we can calculate the destination BE using both the `subTaskId` and `Pos` variables.
If this is a relatively large or complex change, kick off the discussion …
> [optimize](sink) Optimize the BE load balancing logic during concurrent imports.

- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/DorisTypeMapper.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/catalog/DorisTypeMapperTest.java
fix the bug of 'Flink doesn't support converting type BINARY(1) to Doris type yet'.
Issue Number: close #397 
> [fix] Support converting type BINARY of Flink to Doris type (#397)

- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mysql/MysqlDatabaseSync.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/DatabaseSyncTest.java
When including-tables is set to ".*" and excluding-tables is set to "tbl1|tbl2", the exclusion pattern may not work if tables like tbl1 and tbl2 do not have primary keys, resulting in the following error:
```
org.apache.flink.util.FlinkException: Global failure triggered by OperatorCoordinator for 'Source: MySQL Source -> Sink: Writer -> Sink: Committer' (operator cbc357ccb763df2852fee8c4fc7d55f2).
at org.apache.flink.runtime.operators.coordination.OperatorCoordinatorHolder$LazyInitializedCoordinatorContext.failJob(OperatorCoordinatorHolder.java:600)
at org.apache.flink.runtime.operators.coordination.RecreateOnResetOperatorCoordinator$QuiesceableContext.failJob(RecreateOnResetOperatorCoordinator.java:237)
at …
```
> [fix](cdc)fix excluding pattern not working

- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/schema/SchemaChangeManager.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/schema/SchemaManagerITCase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/schema/SchemaManagerTest.java
Issue Number: close #401 
@JNSimba Could you please help me to review this PR?
> [fix] Fix garbled of table or column comments contain Chinese characters(#401)

- flink-doris-connector/src/main/java/org/apache/doris/flink/serialization/RowBatch.java
The typeMismatchMessage method creates a string object describing the error every time, but this object is only used when there is a type mismatch. This impacts performance and memory.
Issue Number: NO
2. Has unit tests been added: No Need
3. Has document been added or modified: No Need
> [improve] modify type judgement statements

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/copy/BatchStageLoad.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/copy/DorisCopyWriter.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/TestUtil.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/batch/TestDorisBatchStreamLoad.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/copy/TestDorisCopyWriter.java
```
[INFO] Running org.apache.doris.flink.sink.copy.TestDorisCopyWriter
02:12:37,489 INFO  org.apache.doris.flink.sink.copy.DorisCopyWriter             [main]  - restore checkpointId 0
02:12:37,490 INFO  org.apache.doris.flink.sink.copy.DorisCopyWriter             [main]  - labelPrefix doris
02:12:37,492 INFO  org.apache.doris.flink.sink.copy.BatchStageLoad              [pool-2-copy-executor-1]  - StageLoadAsyncExecutor start
02:12:37,493 INFO  org.apache.doris.flink.sink.copy.DorisCopyWriter             [main]  - checkpoint arrived, upload buffer to storage
02:12:37,494 INFO  org.apache.doris.flink.sink.copy.DorisCopyWriter             [main]  - checkpoint flush triggered.
02:12:37,497 INFO  org.apache.doris.flink.sink.copy.BatchStageLoad …
```
> (Fix)[case] Fix unstable cases

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/batch/DorisBatchStreamLoad.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisStreamLoad.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/LoadConstants.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/DorisSinkITCase.java
> [improve]improve group commit logic

- flink-doris-connector/src/main/java/org/apache/doris/flink/source/DorisSource.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/source/assigners/SimpleSplitAssigner.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/source/enumerator/DorisSourceEnumerator.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/source/reader/DorisSourceSplitReader.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/source/split/DorisSourceSplit.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/source/split/DorisSourceSplitSerializer.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/source/enumerator/PendingSplitsCheckpointSerializerTest.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/source/reader/DorisSourceReaderTest.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/source/split/DorisSourceSplitSerializerTest.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/source/split/DorisSourceSplitTest.java
When using DorisSource, currently SplitId is the IP address of BE. If it is divided into partitions across BE, duplicate splitIds will appear.
> [Improve] fix doris source duplicate splitid

- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/oracle/OracleDatabaseSync.java
In cdb+pdb mode, when using the cdb username to access, the pdb database and table cannot be accessed, so an error will be reported: `No tables to be synchronized.`
> [Fix] Fix Oracle cdb and pdb model

- flink-doris-connector/src/main/java/org/apache/doris/flink/serialization/RowBatch.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/serialization/TestRowBatch.java
Fixed incorrect Map value reading when key/value is of DATE or DATETIME type.
When encountering the Date type, arrow returns a DateDay Integer, and when encountering the datetime type, arrow returns timestamps of varying precision, including seconds, milliseconds, and microseconds.
> [Fix](source) Fixed incorrect Map value reading when key/value is of DATE or DATETIME type

- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSource.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/source/DorisSourceITCase.java
If Doris's table is
```sql
CREATE TABLE `test_flink` (
`name` VARCHAR(200) NULL,
`age` INT NULL
) ENGINE=OLAP
UNIQUE KEY(`name`)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(`name`) BUCKETS 1
PROPERTIES (
"replication_allocation" = "tag.location.default: 1"
)
```
and FlinkSQL is
```sql
tEnv.executeSql(
"CREATE TABLE doris_source ("
+ "age INT"
+ ") "
+ "WITH (\n"
+ "  'connector' = 'doris',\n"
+ "  'fenodes' = 'xxxx:8030',\n"
+ "  'table.identifier' = 'test.test_flink',\n"
+ "  'username' = 'root',\n"
+ "  'password' = ''\n"
+ ")");
final Table result = tEnv.sqlQuery("SELECT age from doris_source ");
```
The execution plan currently sent is still select * from table, which results in the query data having 2 columns, but the flink schema has only 1 column, and the …
> [Fix] fix projection pushdown

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/batch/DorisBatchStreamLoad.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisStreamLoad.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/LoadConstants.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/DorisSinkITCase.java
Currently streamload supports gz compression in csv format, which requires the client to compress the stream
> [Improve] support gz compress in streamload

- flink-doris-connector/pom.xml
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/deserialize/DorisJsonDebeziumDeserializationSchema.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mongodb/MongoDBDatabaseSync.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mysql/DateToStringConverter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mysql/MysqlDatabaseSync.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/oracle/OracleDatabaseSync.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/oracle/OracleDateConverter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/postgres/PostgresDatabaseSync.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/postgres/PostgresDateConverter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/sqlserver/SqlServerDatabaseSync.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/sqlserver/SqlServerDateConverter.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/CDCSchemaChangeExample.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/utils/DateToStringConverter.java
Issue Number: close #407  #404 #358 
Update flink cdc version to 3.1.1.
Note: Since FLINK-35055 has removed drivers such as mysql/oracle, you need to manually put the corresponding driver package in the <FLINK_HOME>/lib directory when running the whole database synchronization program.
refer to: https://github.com/apache/flink-cdc/pull/3212
If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did …
> [Improve] Update flink cdc version to 3.1.1

- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
When `--schema-change-mode` is not specified, a null pointer problem occurs
> [fix]Fix NPE that occurs when schemaChangeMode is not specified

- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/CdcTools.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSyncConfig.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/SourceConnector.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mongodb/MongoDBDatabaseSync.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mongodb/MongoDateConverter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mysql/DateToStringConverter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mysql/MysqlDatabaseSync.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/oracle/OracleDatabaseSync.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/oracle/OracleDateConverter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/postgres/PostgresDatabaseSync.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/postgres/PostgresDateConverter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/sqlserver/SqlServerDatabaseSync.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/sqlserver/SqlServerDateConverter.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcMongoSyncDatabaseCase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcMysqlSyncDatabaseCase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcOraclelSyncDatabaseCase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcPostgresSyncDatabaseCase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcSqlServerSyncDatabaseCase.java
There is a lot of hard code in the code of synchronizing the whole databases. This method can easily lead to inconsistent configurations on both sides. And it brings a very bad experience to subsequent development or code reading.
> [improve]Improve the hard code in CDC whole database synchronization

- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mongodb/MongoDBSchema.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/mongodb/MongoDBSchemaTest.java
If field's type is decimal type at first, then insert some non decimal type like int, it would cause `Get Decimal precision and Scale error !`.
> [fix][mongodb-cdc]fix replace decimal type error when meeting non decimal type

- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/DorisCatalog.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/doris/DorisSchemaFactory.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/doris/DorisSystem.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/schema/SQLParserSchemaManager.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/JsonDebeziumSchemaSerializer.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/JsonDebeziumChangeContext.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/JsonDebeziumSchemaChange.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/JsonDebeziumSchemaChangeImplV2.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/SQLParserSchemaChange.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/CdcTools.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DorisTableConfig.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mongodb/MongoDBDatabaseSync.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mongodb/serializer/MongoDBJsonDebeziumSchemaSerializer.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/catalog/doris/DorisSchemaFactoryTest.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/catalog/doris/DorisSystemTest.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/schema/SQLParserSchemaManagerTest.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/TestJsonDebeziumSchemaChangeImplV2.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/TestSQLParserSchemaChange.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/DorisTableConfigTest.java
The early table-conf passed a `Map<String, String>` as a parameter, and the parameters included not only the `PROPERTIES()` attributes that can be directly used to create doris tables, but also the data that needs to be parsed as a table creation statement. Such as `table-buckets`.
As a result, in our actual use process, these mixed parameters need to be parsed at various stages, and the logic is also very complicated, because we abstract the parameters of table-conf as a `DorisTableConfig` object
5. Are there any changes that cannot be rolled back: …
> [improve]Improve the hardcode of tableConfig

- flink-doris-connector/src/main/java/org/apache/doris/flink/serialization/RowBatch.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/serialization/TestRowBatch.java
Currently, when reading arrow, since the be layer hard-codes all datetimev2 scales to 6, arrow returns TimeStampMicroVector, which results in scale parsing errors when arrow is displayed. Refer to https://github.com/apache/doris/issues/38174
This PR removes the strong consistency restriction of the type and is compatible with the logic of the scale repaired above
If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose …
> [Fix] fix arrow  read timestamp bug

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/JsonDebeziumSchemaSerializer.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/JsonDebeziumChangeContext.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/JsonDebeziumDataChange.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mongodb/serializer/MongoDBJsonDebeziumSchemaSerializer.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mongodb/serializer/MongoJsonDebeziumDataChange.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/TestJsonDebeziumDataChange.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/TestJsonDebeziumSchemaChangeImpl.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/TestJsonDebeziumSchemaChangeImplV2.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/TestSQLParserSchemaChange.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/MySQLDorisE2ECase.java
In the previous version, when we set `sink.enable-delete=false`, the flink-connector-doris would also synchronize this deleted data to Doris. 
> [cdc] fix enable-delete  option not work

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisStreamLoad.java
Currently, if there is a network problem, an error NoRouteToHost will be reported, but from the jobmanager log, you can't see which be it is connected to, so print it out here
> [Improve](log) add print log for NoRouteToHostException

- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/doris/DorisSchemaFactory.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/doris/DorisSystem.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/copy/CopySQLBuilder.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/schema/SchemaChangeHelper.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/catalog/doris/DorisSchemaFactoryTest.java
The main responsibility of `DorisSystem` should be the data interactive query with doris. We should assign the responsibility of generating table sql to `DorisSchemaFactory`.
> [improve]Improve the way of dorisSystem create table

- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/db2/Db2Schema.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcDb2SyncDatabaseCase.java
When synchronizing data from DB2 to Doris and disabling --single-sink, you may not be able to obtain the column schema via JDBC, which could lead to the failure of creating a table in Apache Doris.
> [cdc] fix create doris table failed when load data from DB2

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/JsonDebeziumSchemaChangeImplV2.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/TestJsonDebeziumSchemaChangeImplV2.java
Currently, when the default value is an empty string, it will be converted to null
> [Fix](schema-chaneg) fix default empty to null

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/schema/SQLParserSchemaManager.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/schema/SQLParserSchemaManagerTest.java
Only the `datetime` type in doris supports setting the default to the current time, and the current time can only be set through the `CURRENT_TIMESTAMP` keyword.
When various upstream data sources synchronize various keywords that set the current time, they are uniformly converted to `CURRENT_TIMESTAMP`
If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what …
> [fix]Fix SQLParser parsing the default value of datetime type as the current time

- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mongodb/MongoDBSchema.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mongodb/MongoDBType.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/mongodb/MongoDBSchemaTest.java
Fix a possible loss of precision when decimal and other number types appear in the same field in the sampled data.
> [fix](cdc) Fix possible loss of precision in MongoCDC Decimal sampling.

- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/JdbcSourceSchema.java
When synchronizing hundreds or even thousands of tables from upstream data, if the data types are not supported in Doris, the connector will directly throw an error. However, it might take users a considerable amount of time to identify the problematic tables. Therefore, this pull request adds some log information to assist users in determining the problem.   …
> [improve]Improve the clarity and detail of the database synchronization logs

- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisExecutionOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/batch/BatchBufferHttpEntity.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/batch/BatchBufferStream.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/batch/BatchRecordBuffer.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/batch/DorisBatchStreamLoad.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/batch/DorisBatchWriter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/copy/BatchRecordBuffer.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/copy/BatchStageLoad.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisConfigOptions.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/cfg/DorisExecutionOptionsTest.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/DorisSinkITCase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/batch/TestBatchBufferHttpEntity.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/batch/TestBatchBufferStream.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/batch/TestDorisBatchStreamLoad.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/copy/TestBatchRecordBuffer.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/table/DorisDynamicTableFactoryTest.java
Optimize data writing in batch mode
1. When the interval is small, streamload will occur frequently. When the amount of data is large, it will cause small writes and back pressure.
Optimized to: schedule thread will not trigger writing when the queue is full
2. Adjust the default values ​​of sink.buffer-flush.max-rows and sink.buffer-flush.max-bytes to 50w and 100MB respectively, and the minimum number of imports (1w) and bytes (10MB) are limited
3. Add back pressure strategy. When the data accumulated in memory exceeds maxBlockByte, block data writing to prevent OOM of flink program
4. The load asynchronous import thread will take out the data in the queue at one time, merge multiple buffers into one buffer, and increase the import throughput.
1. Does it affect …
> [Improve] Fix the problem caused by very small interval in batch mode

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/HttpPutBuilder.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/batch/DorisBatchStreamLoad.java
In batch mode, the label may already exist when importing, and need to regenerate the label when retrying.
```
2024-08-13 13:42:14,888 INFO  org.apache.doris.flink.sink.batch.DorisBatchStreamLoad       [] - load Result {
"TxnId": -1,
"Label": "doris-label2433c8f9-7338-4285-826c-ce2f3dd01f86_17_test_tbl_b592eaaa-8c35-44ba-b959-1538cc78d072",
"Comment": "",
"TwoPhaseCommit": "false",
"Status": "Label Already Exists",
"ExistingJobStatus": "",
"Message": "[LABEL_ALREADY_EXISTS]TStatus: errCode = 2, detailMessage = Label [doris-label2433c8f9-7338-4285-826c-ce2f3dd01f86_17_test_tbl_b592eaaa-8c35-44ba-b959-1538cc78d072] has already been used, relate to txn [1897945320369152]",
"NumberTotalRows": 0,
"NumberLoadedRows": 0,
"NumberFilteredRows": 0,
"NumberUnselectedRows": …
```
> [improvement] fix batch streamload when label already exist

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/BackendUtil.java
The current method of connect doris backend cannot accurately determine whether the port is open. Now, through the GET  method of http, it is more ready to determine whether the `200` response is successful.
> [fix]Fix doris backend connection via http does not take effect

- flink-doris-connector/pom.xml
1. Invalid signature file digest for Manifest main attributes  
fix with this problem when using driver 
3. slimming of arrow flight driver
in arrow-core with 15.0.2 
before package ： 
now package :
> [Fix] Invalid signature file digest for Manifest main attributes  && slimming of arrow flight driver

- flink-doris-connector/pom.xml
in [[Fix] Invalid signature file digest for Manifest main attributes && slimming of arrow flight driver #](https://github.com/apache/doris-flink-connector/pull/472) 。
Due to local Maven cache issues, the effective dependency on Caffeine was removed from the driver
> [Fix] connect arrow with  ClassNotFoundException  by Caffeine

- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mysql/MysqlType.java
Issue Number: close #475
MySQL Type: INTEGER == INT
Append type map to Doris INT
> fix mysql type integer

- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSyncConfig.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DorisTableConfig.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/container/e2e/Doris2DorisE2ECase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcDb2SyncDatabaseCase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcMongoSyncDatabaseCase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcMysqlSyncDatabaseCase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcOraclelSyncDatabaseCase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcPostgresSyncDatabaseCase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/CdcSqlServerSyncDatabaseCase.java
> [Chore] Split some case logic

- flink-doris-connector/src/main/java/org/apache/doris/flink/exception/IllegalArgumentException.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/schema/SchemaChangeHelper.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/schema/SchemaChangeManager.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/schema/SchemaManagerITCase.java
1. Allow modifying a column type that has a default value even if upstream does not carry a default value.
2. Fallback to the original default value if upstream wants to change the default value to others.
Currently, it's not allowed to change a column type that has a default value when upstream does not carry a default value.
If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the …
> [Improve]Support modify column type without default when column exists default value

- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisReadOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSource.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/source/DorisSourceITCase.java
Sometimes when using flinksql for unionall, the following error is reported
```sql
select * from doris_source where name in ('lisi','wangwu') union all SELECT * from doris_source where name = 'zhangsan' 
```
```java
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.ArrayList.rangeCheck(ArrayList.java:659)
at java.util.ArrayList.get(ArrayList.java:435)
at org.apache.doris.flink.deserialization.converter.DorisRowConverter.convertInternal(DorisRowConverter.java:109)
at org.apache.doris.flink.deserialization.RowDataDeserializationSchema.deserialize(RowDataDeserializationSchema.java:51)
at org.apache.doris.flink.source.reader.DorisRecordEmitter.emitRecord(DorisRecordEmitter.java:44)
at …
```
> [Fix](source) fix IndexOutOfBoundsException for union all  

- flink-doris-connector/src/main/java/org/apache/doris/flink/source/DorisSource.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSource.java
#495 Fixed the error of unionall, so it can revert #479
Because DorisSource's resolvedFilterQuery and DorisReadOptiosn's filterQuery will cause confusion
> [Improve] revert pr 479 to remove resolvedFilterQuery in DorisSource

- flink-doris-connector/src/main/java/org/apache/doris/flink/backend/BackendClient.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/rest/PartitionDefinition.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/source/assigners/SimpleSplitAssigner.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/source/reader/DorisValueReader.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/source/reader/ValueReader.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisTableInputSplit.java
When tablet data reading fails, such as openscanner failure, the FLink task will retry. During the retry, some readers (which have not yet done a checkpoint) may lose the tablets they are reading.
> [Bug] Fix retry of lost tablet when tablet read fails

- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/oracle/OracleDatabaseSync.java
When it is not a single-sink, and includeTable=.* and the table name is schema.(tbl1|tbl2), it may exceed the limit of 512 and an error will be reported.
Caused by: java.sql.SQLException: ORA-12733: regular expression too long，
> [fix](oracle-cdc) fix oracle regular expresion too long

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/batch/DorisBatchStreamLoad.java
1. When using DorisBatchWriter to write, when the cache is full, it will be blocked until Flush succeeds. At this time, if be hangs up, the write will continue to fail, and DorisBatchWriter will continue to wait without being awakened, resulting in a stuck state.
3. When be hangs up, streamload will not return a message, and it will be more intuitive to directly throw a response
4. Has unit tests been added: (Yes/No/No Need)
5. Has document been added or modified: (Yes/No/No Need)
6. Does it need to update dependencies: (Yes/No)
7. Are there any changes that cannot be rolled back: (Yes/No) …
> [Fix](batch) Fixed an issue where the writer might be blocked in batch mode

- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisConfigOptions.java
The DorisConfigOptions class has an incorrect description of the "doris.exec.mem.limit" parameter,
Change to correct description
1. Does it affect the original behavior: (Yes/No/I Don't know)  
No
2. Has unit tests been added: (Yes/No/No Need) 
No 
No
No
No
> Edit DorisConfigOptions withDescription

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/batch/DorisBatchStreamLoad.java
Fixed two issues:
1. Since the current cache is global, when there are multiple tables written upstream, such as
tbl1, tbl2, tbl3, when the cached data of the three tables does not reach bufferFlushBytes, but reaches maxBlockBytes, the sinkwriter will be blocked at cache full
When the intervalFlush thread calls the write, it will wait for a long time because it cannot obtain the lock, resulting in the inability to consume the cache.
2. If the flushqueue is full, the sinkwriter will be blocked at flushQueue.put(buffer); at this time, the streamload-executor thread will also call the doflush method after flush, and it will also be stuck because it cannot obtain the lock, and the data cannot be consumed.
> [fix] Fixed the issue that batchwriter may be blocked when writing to multiple tables

- flink-doris-connector/src/main/java/org/apache/doris/flink/lookup/Worker.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/lookup/DorisLookupTableITCase.java
The value type obtained by rs.getObject(index + 1) is inconsistent with the field type obtained by flink Context, resulting in a conversion failure in encapsulating flink RowData. For example, the java type corresponding to TINYINT is Java.lang. Byte, while the java type obtained by rs.getObject(index + 1) is Java.lang. Integer, which has a type conversion problem. SMALLINT had the same problem.
NO
YES
NO
NO
NO …
> [bugfix]Fix a mismatch between the type of jdbc query result and the datatype

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisStreamLoad.java
In some cases, such as be hanging, the exception is usually not thrown directly in the jobmanager, and it is necessary to find the return log in the taskmanager. In some scenarios, the taskmanager log is not easy to locate, so modify:
Before:
```
jobmanager exceptions
Caused by: org.apache.doris.flink.exception.DorisRuntimeException: table test.test_flink_tmp stream load error: null, see more in null
taskmanager.log
11:18:57,428 INFO  org.apache.doris.flink.sink.writer.DorisStreamLoad:    load Result {"status":"FAILED","msg":"errCode = 2, detailMessage = No backend load available., policy: computeNode=false | query=false | load=true | schedule=false | tags= | medium=null"}
11:18:57,429 ERROR org.apache.doris.flink.sink.writer.DorisWriter: Failed to load, table test.test_flink_tmp stream …
```
> [Chore](log) improvment log for stream load

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/schema/SchemaChangeHelper.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/schema/SchemaManagerITCase.java
Fix auto create database failed when it's name contains special symbols.
> [fix] Fix auto create database failed when it's name contains special symbols

- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/doris/DorisSchemaFactory.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/doris/TableSchema.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/CdcTools.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DorisTableConfig.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/container/AbstractE2EService.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/container/e2e/Mysql2DorisE2ECase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/DorisTableConfigTest.java
- flink-doris-connector/src/test/resources/container/e2e/mysql2doris/testMySQL2DorisCreateTable.txt
- flink-doris-connector/src/test/resources/container/e2e/mysql2doris/testMySQL2DorisCreateTable_init.sql
When using CdcTools to automatically create a table, there are some situations where you want to support partition tables.
Doris2.1 version provides the auto partition function, which can be used to complete the creation of partition tables.
You only need to enter the parameters when creating, --table-conf table-partitions=table:partition-column:inteval, such as the following example
--table-conf table-partitions=create_tbl_part_uniq:create_dtime:day,create_tbl_part_dup:create_dtime:month
2. Has unit tests been added: (Yes)
3. Has document been added or modified: (No) …
> [Improve](cdc) support partition table for auto create table

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/LabelGenerator.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/TestLabelGenerator.java
1. When the table name is too long, the concatenated label will be greater than 128 characters.
2. When the table name contains Chinese characters, it cannot be concatenated because the HTTP request header cannot contain Chinese characters.
> [Improve] add label replace when label not meet the specifications 

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/batch/DorisBatchStreamLoad.java
Sometimes, after a streamload error is reported, txn cannot automatically abort. In this case, when retrying with the same label, an error message "label already exists" will be reported. In this case, you need to retry with a different label to avoid ambiguity for users.
```
2024-12-04 09:42:14,208 INFO  org.apache.doris.flink.sink.batch.DorisBatchStreamLoad       [] - load Result {
"TxnId": 6427153,
"Label": "label-doris-ods-loc-oc228108_23_xxx_rt_bba4a7b1-917d-4f05-bb6c-b8db0377ae15_1",
"Comment": "",
"TwoPhaseCommit": "false",
"Status": "Fail",
"Message": "[ANALYSIS_ERROR]TStatus: errCode = 2, detailMessage = get tableList write lock timeout, tableList=(Table [id=6065479, name=xxx_rt, type=OLAP])",
"NumberTotalRows": 814,
"NumberLoadedRows": 814, …
```
> [Improve](batch) change label when batch streamload retry

- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/ConfigurationOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisReadOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/HttpUtil.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/batch/DorisBatchStreamLoad.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/committer/DorisCommitter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisWriter.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/table/DorisDynamicTableFactoryTest.java
1. Fix 307 error
```
Caused by: org.apache.doris.flink.exception.DorisRuntimeException: org.apache.doris.flink.exception.StreamLoadException: stream load error: HTTP/1.1 307 Temporary Redirect
at org.apache.doris.flink.sink.writer.DorisStreamLoad.stopLoad(DorisStreamLoad.java:305) ~[classes/:?]
at org.apache.doris.flink.sink.writer.DorisWriter.prepareCommit(DorisWriter.java:250) ~[classes/:?]
at org.apache.flink.streaming.runtime.operators.sink.SinkWriterOperator.emitCommittables(SinkWriterOperator.java:199) ~[flink-streaming-java-1.18.0.jar:1.18.0]
at org.apache.flink.streaming.runtime.operators.sink.SinkWriterOperator.prepareSnapshotPreBarrier(SinkWriterOperator.java:169) ~[flink-streaming-java-1.18.0.jar:1.18.0]
```
Currently, the default …
> [Improve](http) add timeout  and waitForContinue config  for sink httpclient  

- flink-doris-connector/src/main/java/org/apache/doris/flink/rest/PartitionDefinition.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/rest/RestService.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/source/DorisSource.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/source/reader/DorisFlightValueReader.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/source/reader/ValueReader.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/source/split/DorisSourceSplit.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/rest/TestRestService.java
Support reading catalog table by arrowflight, relying on doris's pr https://github.com/apache/doris/pull/45933
> [Feature] support catalog table read by arrowflightsql

- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/oracle/OracleDatabaseSync.java
Fix the ora-12733 issue when there are many sync tables
> [Fix] Fix the ora-12733 issue when there are many sync tables

- .github/workflows/checkstyle.yaml
Since the code inspection workflow does not specify the Java version, it will fail due to the use of a higher version of Java.
```
Jan 02, 2025 2:31:28 AM com.diffplug.spotless.FormatExceptionPolicyLegacy error
SEVERE: Step 'removeUnusedImports' found problem in 'src/main/java/org/apache/doris/flink/exception/ConnectedFailedException.java':
null
java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at …
```
> Fix code inspection workflow failure

- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/ParsingProcessFunction.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mongodb/MongoDBDatabaseSync.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mongodb/MongoParsingProcessFunction.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/container/ContainerUtils.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/container/e2e/Mysql2DorisE2ECase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/mongodb/MongoParsingProcessFunctionTest.java
- flink-doris-connector/src/test/resources/container/e2e/mysql2doris/testAutoAddTable.txt
- flink-doris-connector/src/test/resources/container/e2e/mysql2doris/testAutoAddTable_init.sql
- flink-doris-connector/src/test/resources/container/e2e/mysql2doris/testMySQL2Doris.txt
- flink-doris-connector/src/test/resources/container/e2e/mysql2doris/testMySQL2DorisByDefault.txt
- flink-doris-connector/src/test/resources/container/e2e/mysql2doris/testMySQL2DorisByDefault_init.sql
- flink-doris-connector/src/test/resources/container/e2e/mysql2doris/testMySQL2DorisCreateTable.txt
- flink-doris-connector/src/test/resources/container/e2e/mysql2doris/testMySQL2DorisCreateTable_init.sql
- flink-doris-connector/src/test/resources/container/e2e/mysql2doris/testMySQL2DorisEnableDelete.txt
- flink-doris-connector/src/test/resources/container/e2e/mysql2doris/testMySQL2DorisEnableDelete_init.sql
- flink-doris-connector/src/test/resources/container/e2e/mysql2doris/testMySQL2DorisMultiDb2One.txt
- flink-doris-connector/src/test/resources/container/e2e/mysql2doris/testMySQL2DorisMultiDb2One_init.sql
- flink-doris-connector/src/test/resources/container/e2e/mysql2doris/testMySQL2DorisMultiDbSync.txt
- flink-doris-connector/src/test/resources/container/e2e/mysql2doris/testMySQL2DorisMultiDbSync_init.sql
- flink-doris-connector/src/test/resources/container/e2e/mysql2doris/testMySQL2DorisSQLParse.txt
- flink-doris-connector/src/test/resources/container/e2e/mysql2doris/testMySQL2DorisSQLParse_init.sql
- flink-doris-connector/src/test/resources/container/e2e/mysql2doris/testMySQL2Doris_init.sql
When synchronizing multiple databases, not writing --database may cause null pointer errors
When synchronizing multiple databases, there are two scenarios
1. Synchronize multiple upstream databases to one database of doris
```
--database dorisdb
--mysql-conf database-name db.*
```
Note: Currently, if multiple databases have tables with the same name, similar to the scenario of sharding, they will be written to the same downstream table
2. Write multiple upstream databases to multiple downstream databases
No need to specify `--database`
Just specify `--mysql-conf database-name db.*`
4. Does it need to …
> [Fix] fix multi database sync npe error

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/HttpUtil.java
[fix] Fix error like:
Caused by: org.apache.http.ProtocolException: Transfer-encoding header already present
at org.apache.http.protocol.RequestContent.process(RequestContent.java:93) ~[xxx-cdh-flink1-20-0-sql-gitlab-runner-1.0.0.jar:?]
at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:132) ~[xxx-cdh-flink1-20-0-sql-gitlab-runner-1.0.0.jar:?]
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:182) ~[xxx-cdh-flink1-20-0-sql-gitlab-runner-1.0.0.jar:?]
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[xxx-cdh-flink1-20-0-sql-gitlab-runner-1.0.0.jar:?]
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[xxx-cdh-flink1-20-0-sql-gitlab-runner-1.0.0.jar:?]
at …
> [fix] Fix error like:aused by: org.apache.http.ProtocolException: Transfer-encoding header already present

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/HttpUtil.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisStreamLoad.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/LabelGenerator.java
Issue Number: close #536 
When the http thread fails, the main thread will not be able to perceive the exception, which may cause write blocking. In this case, you can enable the `sink.check-interval` time (must lagre than 1000)
This pr is used to optimize the situation when the check-interval thread is closed (or the `sink.check-interval` is relatively large)
taskmanager log:
```
2025-01-07 14:05:33,608 INFO  org.apache.doris.flink.sink.writer.RecordBuffer              [] - start buffer data, read queue size 0, write queue size 3
2025-01-07 14:05:33,608 INFO  org.apache.doris.flink.sink.writer.DorisStreamLoad           [] - table ods_gof_event_ri stream load started for doris_event_test1736229876676_test_xxxx_0_2 on host 1.1.1.1:8030
2025-01-07 14:05:33,608 INFO …
```
> [Fix] When http reports an error, writing will get stuck

- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mongodb/MongoDBDatabaseSync.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/mongodb/MongoDBDatabaseSyncTest.java
Issue Number: close #541
Add MIN_SAMPLE_SIZE MAX_SAMPLE_SIZE parameters to dynamically adjust the size of sampleSize samples, so that it can sample more accurately when it is a small table, and consume less sampling resources when it is a large table
> [improve] Optimize MongoCDC sampleSize calculation logic

- flink-doris-connector/src/main/java/org/apache/doris/flink/rest/models/BackendV2.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/rest/models/Field.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/rest/models/QueryPlan.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/rest/models/Schema.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/rest/models/Tablet.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/rest/TestRestService.java
In some cases, the API will return more fields, like https://github.com/apache/doris/pull/46557. In this case, strict validation may result in errors. We can set it to ignore.
> [Improvement] add resposne ignore field config

- flink-doris-connector/src/main/java/org/apache/doris/flink/rest/RestService.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSource.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/source/DorisSourceITCase.java
Issue Number: close #545 
Currently, pushdown can only push down predicates.
For example, the calculation of complex functions also needs to be pushed down, but such functions cannot be exhaustive, so you can use the previous doris.filter.query option to splice the pushed down and the user-input to complete the function pushdown.
If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what …
> [improve] Concat doris.filter.query option when push down 

- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisReadOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/source/reader/DorisFlightValueReader.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/source/reader/DorisValueReader.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSource.java
There is the following flinksql
```select * from table limit 10```
When doris has a large data table, it will first scan all the data in the table, and then make a limit.
Here you can push the limit down to reduce the amount of data scanned.
Note that this is only partially pushed down, so the scanned data and the limit value may not be equal (For example, under multiple tablets, the scanned data will be greater than the limit value), and it will eventually rely on the upper-level Limit of FlinkSQL to do it
5. Are there any changes that cannot be …
> [Improve] add partial limit push down

- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/batch/DorisBatchStreamLoad.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/batch/DorisBatchWriter.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/batch/TestDorisBatchStreamLoad.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/batch/TestDorisBatchWriter.java
1. When the checkpoint is flushed, the buffermap may be empty, but it is also necessary to wait for the load thread to complete.
2. When the streamload fails, before the flushqueue is cleared. The main thread is blocked at flushQueue.put(buffer); if the streamload fails at this time, the flushqueue will be cleared, and the main thread will be unblocked. Since there is no checkFlushException at this time, the checkpoint may be considered normal, and data may be lost later.
If this is a …
> [Fix] improve batch mode when streamload failed

- flink-doris-connector/src/main/java/org/apache/doris/flink/catalog/doris/DorisSchemaFactory.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/JsonDebeziumSchemaSerializer.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/JsonDebeziumChangeContext.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/JsonDebeziumSchemaChange.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/JsonDebeziumSchemaChangeImplV2.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/SQLParserSchemaChange.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/DatabaseSync.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/ParsingProcessFunction.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/converter/TableNameConverter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mongodb/MongoParsingProcessFunction.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/serializer/jsondebezium/TestJsonDebeziumSchemaChangeImplV2.java
In the current scenario of database and table sharding, when single-sink is enabled, 
the configurations for MultiToOneOrigin and MultiToOneTarget cannot be utilized during automatic table creation.
> [Featuer] support auto create table for shard table

- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/ConfigurationOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisReadOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/rest/RestService.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/source/reader/ValueReader.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisConfigOptions.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/rest/TestRestService.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/source/DorisSourceITCase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/table/DorisDynamicTableFactoryTest.java
By default, the reading method is changed to arrowflightsql. If the port is not obtained, it will degenerate to thrift reading.
> [Improve] DorisSource use arrowflightsql read type default

- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisExecutionOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisWriter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisConfigOptions.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/container/AbstractITCaseService.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/DorisSinkFailoverITCase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/DorisSinkMultiTblFailoverITCase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/utils/MockMultiTableSource.java
Previously, when importing multiple tables, check-interval was turned off because the check thread and preparecommit thread might cause conflicts.
However, in extreme cases, this may cause the asynchronous http thread to exit, but the main thread is blocked by the recordBuffer queue until the checkpoint times out and restarts the task.
So this pr mainly solves the following problems:
1. Enable the check-interval thread by default
2. Add a mutex between the check thread and prepareCommit to ensure that the check method is not executed during preparecommit.
3. Add exception cases for multi-table import (dynamically add tables/restart Doris/checkpoint failure/streamload failure)
5. Has unit tests been added: (Yes/No/No Need)
6. …
> [Improve](sink) Fix problems  may be caused by multi table import and add cases

- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisExecutionOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/exception/LabelAlreadyExistsException.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisStreamLoad.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/DorisWriter.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/LoadConstants.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/RecordBuffer.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/RecordStream.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisConfigOptions.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/DorisSinkMultiTblFailoverITCase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/sink/writer/TestDorisWriter.java
Currently, we rely on the check-interval thread to periodically check whether the http thread of streamload is alive.
This will cause the following problems:
In corner cases, if the data of a checkpoint is exactly equal to the size of `bufferCount*bufferSize`, the flink program will be stuck. 
like this case `DorisSinkMultiTblFailoverITCase.testTableNotExistCornerCase`, If [here](https://github.com/apache/doris-flink-connector/pull/578/files#diff-a152da68177535d9c8bbe156405cf32674f8a629a42ccf9906c5ac099d46993eL370-L374) is not interrupted, it will continue to be blocked until the checkpoint times out and is restarted.
jstack is as follows. At this time, the checkdone thread detects that it has entered prepareCommit and will not check.
```java …
```
> [Improve](Stream) Optimize the situation where Flink may get stuck after the streamload thread exits abnormally

- flink-doris-connector/src/main/java/org/apache/doris/flink/backend/BackendClient.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/ConfigurationOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisReadOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisConfigOptions.java
- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableFactory.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/source/DorisSourceITCase.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/table/DorisDynamicTableFactoryTest.java
```
Caused by: org.apache.doris.shaded.org.apache.thrift.transport.TTransportException: MaxMessageSize reached
    at org.apache.doris.shaded.org.apache.thrift.transport.TEndpointTransport.checkReadBytesAvailable(TEndpointTransport.java:81)
    at org.apache.doris.shaded.org.apache.thrift.protocol.TBinaryProtocol.checkStringReadLength(TBinaryProtocol.java:444)
    at org.apache.doris.shaded.org.apache.thrift.protocol.TBinaryProtocol.readStringBody(TBinaryProtocol.java:415)
    at org.apache.doris.shaded.org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:256)
    at org.apache.doris.shaded.org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:77)
    at org.apache.doris.sdk.thrift.TDorisExternalService$Client.recvGetNext(TDorisExternalService.java:92 …
```
> [Improve] add thrfit max message size option

- flink-doris-connector/src/main/java/org/apache/doris/flink/tools/cdc/mongodb/MongoDBSchema.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/tools/cdc/mongodb/MongoDBSchemaTest.java
Previously, all numeric types were converted to Decimal to prevent precision loss when syncing mixed-type fields from MongoDB to Doris. This caused unnecessary precision degradation for single-type fields. For example, if the initial table has a small amount of data and an INT-type field with all values below 1000, after conversion to DECIMAL, the numeric precision will be limited to 3 digits. If the data evolves with business growth and the field value later exceeds 1000 (e.g., becomes a 4-digit number), it will lose precision due to the previously inferred limited length.
This commit improves the type inference logic:
- Only convert to Decimal if multiple types are present in the sampled data;
- Retain original types (e.g., INT, BIGINT) for fields with consistent data types;
1. Does it …
> [Improve]:(MongoDB)optimize type inference to avoid unnecessary decimal conversion

- flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicOutputFormat.java
> [Pick] Pick flink's date data type

- flink-doris-connector/src/main/java/org/apache/doris/flink/deserialization/converter/DorisRowConverter.java
- flink-doris-connector/src/test/java/org/apache/doris/flink/deserialization/convert/DorisRowConverterTest.java
Issue Number: #605 
`org.apache.doris.flink.deserialization.converter.DorisRowConverter#convertArrayData` ad recursive processing logic for nested ArrayData types
2. Has unit tests been added: (Yes)
> [Improve] support nested type fields in ArrayData
